### ISSUE TITLE
主页布局错误

### ISSUE THREAD

**Issue by Steven-WZH** [liuzhihang/halo-theme-hao#100]
### 是什么版本出现了此问题？

1.0.8

### 在线站点地址

https://blog.steven.tk

### 发生了什么？

![image](https://user-images.githubusercontent.com/113268133/218254434-3d91dfe3-5e7a-4c08-9d73-20d032d66a11.png)
![image](https://user-images.githubusercontent.com/113268133/218254452-963f97dc-7a7e-445f-a028-21544f5f7671.png)
主页右边少了2个文章

**Comment by AirboZH** [comment]
主题设置 - 文章 - 阅读建议 的数量会影响这个地方文章的个数
由 #76 这次变动引起

**Comment by Steven-WZH** [comment]
好的，解决了
还有一问题，请问手机端的侧栏里面的专栏为啥不显示
![image](https://user-images.githubusercontent.com/113268133/218264138-fc4aa6ad-468c-4c88-93e5-a5ba7c0ef7dc.png)

**Comment by AirboZH** [comment]
@Steven-WZH 我一会看一下吧

**Comment by Steven-WZH** [comment]
好，不急
