### ISSUE TITLE
菜单项必须填写链接地址，主菜单项也必须是`<a>`标签，这会导致在移动端点击主菜单展开下拉子菜单时，必定会产生跳转，导致子菜单项无法点击

### ISSUE THREAD

**Issue by AirboZH** [liuzhihang/halo-theme-hao#104]

**Comment by AirboZH** [comment]
移动端适配了侧栏，如果移动端访问桌面页面导致这个问题，目前没用很好的解决办法

**Comment by sun0225SUN** [comment]
> 移动端适配了侧栏，如果移动端访问桌面页面导致这个问题，目前没用很好的解决办法

哈哈，我是用平板访问时发现的bug。

其实有解决方法，但是目前我不会写。

思路大致如下

判断层级是否有子菜单，如果有的话，模板中就不加 a 标签了（可以换成span。

**Comment by AirboZH** [comment]
> > 移动端适配了侧栏，如果移动端访问桌面页面导致这个问题，目前没用很好的解决办法
> 
> 哈哈，我是用平板访问时发现的此bug。
> 
> 其实有解决方法，但是目前我不会写。
> 
> 思路大致如下
> 
> 判断层级是否有子菜单，如果有的话，模板中就不加 a 标签了（可以换成span。

可是标签夜 /tags 也是一个页面😭
