### ISSUE TITLE
手机端文章详情页侧栏无法打开

### ISSUE THREAD

**Issue by Steven-WZH** [liuzhihang/halo-theme-hao#113]
### 是什么版本出现了此问题？

1.0.8

### 在线站点地址

https://blog.steven.tk

### 发生了什么？

如题

**Comment by AirboZH** [comment]
正常版本是没有这个问题的
![image](https://user-images.githubusercontent.com/50261327/218925413-5d7b4732-abda-409b-a0b9-c2dc5ce1e112.png)

根据console发现报错在 main.js 的 button addEventListener
发现**main.js似乎经过压缩**

![image](https://user-images.githubusercontent.com/50261327/218926103-a7489423-c7fe-41fd-b786-b20dffed8ecf.png)

curl 发现

```shell
airbo@WinBook:~$ curl -I https://blog.steven.tk/themes/theme-hao/assets/js/main.js
HTTP/2 200
date: Wed, 15 Feb 2023 04:05:01 GMT
content-type: application/javascript
……
server: cloudflare
……
```

有一层cloudflare CDN服务，应该是cloudflare 提供的js压缩功能导致

----

但是引起错误的根本原因是 `document.getElementById('mobile-toc-button').addEventListener` ，这个 `mobile-toc-button` 似乎在hao中没有移植过来。

我回头验证可以删除后可能会移除这段代码

**Comment by Steven-WZH** [comment]
现在怎么解决捏，我把cf的压缩js关了还是会出现这个问题
![image](https://user-images.githubusercontent.com/113268133/219679961-b8ef6ab8-6736-4a92-aa7c-373efa4cfcf9.png)

**Comment by Steven-WZH** [comment]
解决了，把这里关掉就行了
![image](https://user-images.githubusercontent.com/113268133/219681087-a8632d25-76ed-4e60-9b53-3736929755c6.png)
