### ISSUE TITLE
建站天数显示错误

### ISSUE THREAD

**Issue by WekyJay** [liuzhihang/halo-theme-hao#120]
### 是什么版本出现了此问题？

1.0.8-1.0.9

### 在线站点地址

https://www.wekyjay.cn/

### 发生了什么？

![image](https://user-images.githubusercontent.com/20734333/219858104-abd921a0-fdef-4244-bafe-ca9f4d8e51ef.png)
建站天数显示为建站日期。我想应该是一个BUG吧?

**Comment by sun0225SUN** [comment]
`/www/server/nginx/proxy_cache_dir`

这是因为缓存造成的，删除此目录即可

**Comment by WekyJay** [comment]
已修复，谢谢！
