### ISSUE TITLE
赞助功能

### ISSUE THREAD

**Issue by Steven-WZH** [liuzhihang/halo-theme-hao#123]
### 你当前使用的版本

1.0.9

### 描述一下此特性

在文章末尾加一个赞助按钮，鼠标放上去会出现一个二维码（不要太大），二维码可以在后台从附件里设置

**Comment by Steven-WZH** [comment]
![image](https://user-images.githubusercontent.com/113268133/220618660-e9c12ca2-35f3-447c-be3b-72feaff539fc.png)

**Comment by liuzhihang** [comment]
是不是可以考虑直接在文章里面贴二维码？这个赞助功能吧，说实话，用处不大。
