### ISSUE TITLE
弹窗无法关闭

### ISSUE THREAD

**Issue by kcaco2000** [liuzhihang/halo-theme-hao#128]
### 是什么版本出现了此问题？

 1.0.9

### 在线站点地址

https://www.kcaco.top

### 发生了什么？

弹窗设置关闭后，还是会弹出。
![image](https://user-images.githubusercontent.com/42790380/222192785-f50d3589-17d3-4b64-9703-60f7c49444e7.png)
![image](https://user-images.githubusercontent.com/42790380/222193487-6a956343-d761-4ed8-939b-e82c0d9908d4.png)

分类、标签页面显示不对。
![image](https://user-images.githubusercontent.com/42790380/222192938-95f3c961-11b9-413e-a8fb-f5de6309c8ad.png)

**Comment by lanbinshijie** [comment]
好的，我们将尝试在下一个版本修复这个问题。您可以先将标题和内容都设置为空或您想要的内容来暂时解决这个问题。
