### ISSUE TITLE
自定义界面侧栏组件页面占比

### ISSUE THREAD

**Issue by Steven-WZH** [liuzhihang/halo-theme-hao#131]
### 是什么版本出现了此问题？

1.0.9

### 在线站点地址

https://blog.stevenw.cc/contact

### 发生了什么？

![image](https://user-images.githubusercontent.com/113268133/222881686-53964a0a-f470-47f1-928b-5b01320b6860.png)
能否把页面比例调整下

**Comment by lanbinshijie** [comment]
好的，我们将尝试在下一个版本修复它

**Comment by sun0225SUN** [comment]
可以自定义`CSS`然后使用`代码注入`功能实现
