### ISSUE TITLE
主题设置【导航左侧相关链接】和【页脚底部相关连接】选择主菜单后不能取消

### ISSUE THREAD

**Issue by bj-houzhenyu** [liuzhihang/halo-theme-hao#136]
### 是什么版本出现了此问题？

1.0.9

### 发生了什么？

希望能取消选中

### 附加信息

![image](https://user-images.githubusercontent.com/64603697/223602627-56dee160-63b7-491a-80d2-321adb555b8f.png)

![image](https://user-images.githubusercontent.com/64603697/223602678-bfe4c211-b4db-4cfd-b39d-48017e378d4b.png)

会导致这个取消不了
![image](https://user-images.githubusercontent.com/64603697/223602807-0d215ea0-cff8-45f1-8430-22d1c980b079.png)

**Comment by baozishu** [comment]
菜单多增加 几个菜单 主菜单确定就好

**Comment by bj-houzhenyu** [comment]
> 

好的，感谢已关闭
