### ISSUE TITLE
edge 浏览器不能正常显示页脚？

### ISSUE THREAD

**Issue by infanx** [liuzhihang/halo-theme-hao#140]
### 是什么版本出现了此问题？

1.0.9

### 在线站点地址

https://www.infanx.com/

### 发生了什么？

edge 浏览器
![image](https://user-images.githubusercontent.com/65985757/224550293-b74a08e5-6ba4-4b0e-9729-49b07e1e37d1.png)
chrome 浏览器
![image](https://user-images.githubusercontent.com/65985757/224550326-e8ee2673-b2d8-46f6-bdd4-ecbb998086e5.png)

**Comment by AirboZH** [comment]
这是一个已知的问题，似乎页脚会被广告拦截插件拦截掉。目前的解决方式就是将网站加入插件白名单

**Comment by infanx** [comment]
> 这是一个已知的问题，似乎页脚会被广告拦截插件拦截掉。 目前的解决方式就是将网站加入插件白名单

好像确实是广告拦截插件的锅
在用户过滤器里面加上 `#@##footer-banner` 就好了
