### ISSUE TITLE
在文章显示中添加latex公式

### ISSUE THREAD

**Issue by L4v3nder** [liuzhihang/halo-theme-hao#142]
### 你当前使用的版本

2.3.0

### 描述一下此特性

latex公式可以显示较好排版格式的数学公式。

**Comment by sun0225SUN** [comment]
后续默认编辑器和ByteMD编辑器均会支持，先关上了哈

https://github.com/halo-sigs/richtext-editor/issues/14#issuecomment-1592807079

![image](https://github.com/liuzhihang/halo-theme-hao/assets/79169717/12445129-c6ac-4b44-9f22-49fd5665ad65)
