### ISSUE TITLE
代码高亮插件不起作用

### ISSUE THREAD

**Issue by dh-free** [liuzhihang/halo-theme-hao#146]
### 是什么版本出现了此问题？

halo2.0.3

### 在线站点地址

https://blog.elites.ink/

### 发生了什么？

我加载了[prism.js](https://blog.elites.ink/console/#/plugins/PluginPrismJS/detail)这个插件，前端文章详情页代码并没有高亮
![image](https://user-images.githubusercontent.com/48708512/227099323-89c2fec9-7878-4cea-a7d2-85db4882d6d8.png)
![image](https://user-images.githubusercontent.com/48708512/227099343-f18ccab9-a87d-443b-bb69-67124482d009.png)

**Comment by baozishu** [comment]
富文本 还是 MD
MD需要格式

**Comment by dh-free** [comment]
> 富文本 还是 MD MD需要格式

![image](https://user-images.githubusercontent.com/48708512/227141289-20fdec13-a3f5-4de2-8ef5-7078e2bd21c6.png)
后台都能渲染出来

**Comment by Jackchen0514** [comment]
怎么解决呢，我也遇到了这个问题

**Comment by testnet0** [comment]
同样的问题，代码文章不能渲染，在后台就是可以

**Comment by shy-share** [comment]
> 同样的问题，代码文章不能渲染，在后台就是可以

@testnet0 你用的是哪个代码高亮插件？

**Comment by testnet0** [comment]
>

> > 同样的问题，代码文章不能渲染，在后台就是可以
> 
> @testnet0 你用的是哪个代码高亮插件？

官方和第三方的都试了 现在换其他主题了
