### ISSUE TITLE
建站天数在详情页内显示为建站日期

### ISSUE THREAD

**Issue by liux-pro** [liuzhihang/halo-theme-hao#147]
### 是什么版本出现了此问题？

1.0.9

### 在线站点地址

https://liuzhihang.com/

### 发生了什么？

建站天数在详情页内显示为建站日期
随意打开两个页面
https://liuzhihang.com/
https://liuzhihang.com/archives/curator-4
![image](https://user-images.githubusercontent.com/20764978/227710263-59617dd9-1bb9-43f6-8ac4-3bf4e496ece6.png)
![image](https://user-images.githubusercontent.com/20764978/227710267-e8af9013-0abd-4264-a964-a70a47517869.png)

**Comment by xyhcode** [comment]
`GLOBAL_CONFIG.isPost` 是`main.js`这个判断的问题,在主页时返回的是`false` 在文章页面时返回的是`true` ，不用把`addRuntime()`放判断里面 应该就可以解决
<img width="660" alt="image" src="https://user-images.githubusercontent.com/64968400/229099466-9ef21457-1fba-45ce-911e-50f23ed8fad3.png">
