### ISSUE TITLE
首页部分JS动画异常（不生效）

### ISSUE THREAD

**Issue by wygwyggit** [liuzhihang/halo-theme-hao#148]
### 是什么版本出现了此问题？

1.0.9

### 在线站点地址

http://42.194.184.12:8090/

### 发生了什么？

首页，今日推荐。鼠标移出不显示大图。
滚动页面，顶上的数字还是0
滚动页面，顶部固定快中间不显示名称。

### 附加信息

<img width="546" alt="image" src="https://user-images.githubusercontent.com/52059667/227972253-8090ba65-a3e9-4520-b8ec-ba425dca85a4.png">
这些方法没有成功的被执行

**Comment by AirboZH** [comment]
这可能是由于你还没有发布任何文章导致的，请发布文章后看一下是否还有这个问题
