### ISSUE TITLE
前端JS错误

### ISSUE THREAD

**Issue by kuerme** [liuzhihang/halo-theme-hao#152]
### 是什么版本出现了此问题？

1.0.9

### 在线站点地址

https://liuzhihang.com/

### 发生了什么？

![2020-06-04_23-02-21](https://user-images.githubusercontent.com/2811986/228434605-7b2b6d80-8e18-4af7-a5a8-04a91b67b9dc.png)

### 相关日志输出

```shell
在 https://liuzhihang.com/ 自行查看，我自己安装的版本也是同样的问题；
```

**Comment by xyhcode** [comment]
```
var postName = document.getElementsByClassName("post-title")[0]; 
```
有没有可能postName返回的是undefined
