### ISSUE TITLE
BUG反馈 标签文字出现在了不该出现的地方

### ISSUE THREAD

**Issue by mobeiCanyue** [liuzhihang/halo-theme-hao#164]
### 是什么版本出现了此问题？

1.1.0

### 发生了什么？

![image](https://user-images.githubusercontent.com/81098819/231210627-a696b921-b3ad-4d78-9d44-1b23d01041f0.png)

**Comment by AirboZH** [comment]
已处理，下个版本修复

**Comment by AirboZH** [comment]
#163
