### ISSUE TITLE
瞬间 分类 标签 

### ISSUE THREAD

**Issue by baozishu** [liuzhihang/halo-theme-hao#171]
### 是什么版本出现了此问题？

1.1.1

### 在线站点地址

https://1p.ono.ee

### 发生了什么？

[![oXwE1u.png](https://www.helloimg.com/images/2023/04/16/oXwE1u.png)](https://www.helloimg.com/image/oXwE1u)
[![oXweOQ.png](https://www.helloimg.com/images/2023/04/16/oXweOQ.png)](https://www.helloimg.com/image/oXweOQ)
[![oXwqrt.png](https://www.helloimg.com/images/2023/04/16/oXwqrt.png)](https://www.helloimg.com/image/oXwqrt)

**Comment by Steven-WZH** [comment]
瞬间显示错误 把缓存清一下就好了
