### ISSUE TITLE
代码编辑时完全空白不好看

### ISSUE THREAD

**Issue by shuaipotian-joke** [liuzhihang/halo-theme-hao#172]
### 是什么版本出现了此问题？

v1.1.1

### 在线站点地址

https://chenweilin.cn/archives/springboot

### 发生了什么？

不管用什么编辑器都会出现以下问题
![image](https://user-images.githubusercontent.com/60846491/232456499-62e3e908-b946-492c-a656-7b57976282d1.png)

### 相关日志输出

```shell
无
```

### 附加信息

无

**Comment by Yooona-Lim** [comment]
这个不是BUG，建议改成“新特性建议”

**Comment by shuaipotian-joke** [comment]
> 这个不是BUG，建议改成“新特性建议”
您的意思是说，大家都会这样吗，我是觉得只有我会这样才这么说的，因为这样不好看，我看了主题作者的博客并没有这样的问题，请告诉我是我那个地方配置出了问题？

**Comment by shuaipotian-joke** [comment]
他的博客是这样的
![image](https://user-images.githubusercontent.com/60846491/233535852-7407be0b-2812-4dd6-b0f0-fc21ece047cf.png)
wod我的是这样的
![image](https://user-images.githubusercontent.com/60846491/233535902-9e914d6d-91a3-4c0e-a6c6-e3e10712918e.png)

**Comment by sun0225SUN** [comment]
需要安装代码高亮插件的

**Comment by shuaipotian-joke** [comment]
> 需要安装代码高亮插件的
我安装了高亮插件显示还是这样，只不过文字有颜色了而已
![image](https://user-images.githubusercontent.com/60846491/233594457-eb1cb821-78ec-4195-bf26-c4129da6426b.png)

**Comment by shuaipotian-joke** [comment]
> 你安装的哪个插件哇，叫啥名，可能和主题不适配。 我装的这个：https://github.com/liuzhihang/plugin-prismjs
可以了，感谢热心老哥！你别说，这个插件我在应用市场找不到，不过解决了哈哈，谢谢兄弟
