### ISSUE TITLE
在导航栏右边添加一个用户图标，以便新用户注册登录

### ISSUE THREAD

**Issue by mobeicanyue** [liuzhihang/halo-theme-hao#173]
### 描述一下此特性

在导航栏右边添加一个用户图标，以便新用户注册登录（找了一下发现是没有用户登录注册按钮的，只能让用户输入/console到后台）

**Comment by Yooona-Lim** [comment]
可以类似于这种
![image](https://user-images.githubusercontent.com/81098819/233123262-ec847925-dbbc-472a-9dda-529ac9bd1c71.png)

**Comment by lanbinshijie** [comment]
该功能已经实现，预计将会在下一个版本推出，按钮放置在了中控台的最后一项。
PR：#392

**Comment by lanbinshijie** [comment]
@sun0225SUN @Roozenlz 可以关闭该issue
