### ISSUE TITLE
升级新版本主题之后，前端首页内容错位

### ISSUE THREAD

**Issue by leyedu** [liuzhihang/halo-theme-hao#176]
### 是什么版本出现了此问题？

1.0.9

### 在线站点地址

https://cn.10691.cn/

### 发生了什么？

升级最新主题之后，前端首页内容显示标签与内容重叠。

**Comment by leyedu** [comment]
![微信图片_20230424103832](https://user-images.githubusercontent.com/75716855/233888359-48a4c1a2-f02f-441e-b3bd-4aae615dace6.png)

**Comment by AirboZH** [comment]
已修复的问题 建议更新css文件缓存
