### ISSUE TITLE
分类不支持树状菜单

### ISSUE THREAD

**Issue by wyl985** [liuzhihang/halo-theme-hao#177]
### 是什么版本出现了此问题？

halo2.4.0

### 发生了什么？

![image](https://user-images.githubusercontent.com/31380874/234156416-c6d661ad-9aaf-4a6f-ba13-4cb4b8a8c3af.png)
![image](https://user-images.githubusercontent.com/31380874/234157769-5dc086ce-7603-4347-a52c-be9ec3a2bb8c.png)

**Comment by jkjoy** [comment]
原版就不支持的吧

**Comment by jkjoy** [comment]
而且菜单不是在顶部么

**Comment by wyl985** [comment]
![image](https://github.com/liuzhihang/halo-theme-hao/assets/31380874/441b715f-51db-44f1-8283-df0e946b2dfc)
![image](https://github.com/liuzhihang/halo-theme-hao/assets/31380874/54fa1ff7-9612-4cb6-9049-4730798c610c)
原版使用的Earth主题是支持树状分类的

**Comment by jkjoy** [comment]
都说了原版的主题是不支持的~何况这个是移植的.原版是啥样 移植的就是什么样! 这不明白么

**Comment by AirboZH** [comment]
代码参考 [Hexo-Theme-Acrylic-Next](https://github.com/hexo-theme-Acrylic/Hexo-Theme-Acrylic-Next) 
目前应该没有计划支持 树状菜单
