### ISSUE TITLE
移动端不显示导航，侧边栏建议加上

### ISSUE THREAD

**Issue by mobeicanyue** [liuzhihang/halo-theme-hao#178]
### 描述一下此特性

如果移动端的首页不能加导航栏，建议在侧边栏加上，因为有特定的功能需求，谢谢开发大大！
![Screenshot_2023-04-29-00-53-26-148_com chrome dev-edit](https://user-images.githubusercontent.com/81098819/235207960-9c0c1534-c603-488b-8d05-7c9538cc6c68.jpg)

**Comment by Steven-WZH** [comment]
新建一个菜单
![image](https://github.com/liuzhihang/halo-theme-hao/assets/113268133/8dfc54f3-ac73-44b8-8b07-36f8424af0a1)
在设置里选中
![image](https://github.com/liuzhihang/halo-theme-hao/assets/113268133/4fcc9449-aeac-4f81-9c53-80934178f572)
效果：
![image](https://github.com/liuzhihang/halo-theme-hao/assets/113268133/557f5e7b-fff6-4004-85b7-d392cff7494e)

注意只有二级菜单才作为链接会显示在侧栏，一级菜单作为分类
![1685104841177](https://github.com/liuzhihang/halo-theme-hao/assets/113268133/e4375806-73ab-4ce0-8ead-d1cc42945b9d)
