### ISSUE TITLE
自定义界面样式缺少

### ISSUE THREAD

**Issue by Steven-WZH** [liuzhihang/halo-theme-hao#181]
### 是什么版本出现了此问题？

1.1.1

### 在线站点地址

https://blog.stevenw.cc/contact/

### 发生了什么？

![image](https://github.com/liuzhihang/halo-theme-hao/assets/113268133/b5d7ce07-6c2c-4c15-8f1b-990015542608)
![image](https://github.com/liuzhihang/halo-theme-hao/assets/113268133/8552e294-54cd-4995-a96a-c3aeebaeabf7)
缺少一些格式的加载，比如此处的无序列表

**Comment by sun0225SUN** [comment]
请问这个问题还存在吗，看你的网站已经正常了

顺带提一下，新版本 `v1.1.2 —— v1.1.4`  需要先自定义一个页面然后设置相应模板才可以生效，后续文档教程会跟进

![image](https://github.com/liuzhihang/halo-theme-hao/assets/79169717/813fc7b9-0924-4719-a66d-b99a4e88b02d)
