### ISSUE TITLE
js 和 图片托管到github通过jsdriver cdn加速访问

### ISSUE THREAD

**Issue by laiqinghua** [liuzhihang/halo-theme-hao#182]
### 你当前使用的版本

v1.1.1

### 描述一下此特性

需求背景： 90%小站都是2M 1M的带宽，速度非常慢，站长也舍不得上CDN加速。我们很多js和css  图片都非常大，即使使用nginx压缩后还是蛮大，对于一个小站来说打开时间会慢慢变慢。  建议将JS CSS 图片托管到github上，通过jsdriver加速来提高访问效率。

1. 建议在后台主题中设置，提供两个选项JS图片加速和默认源站提供访问。
2. 默认源站提供访问则是保持当前的js css 图片提供访问，提供在项目源码中返回给客户端。
3. 选择jsdriver加速，则需要你们单独维护一个github js css 图片仓库，在主题设置中开启后将会使用一个url来加载css和js以及图片。

**Comment by sun0225SUN** [comment]
可以加CDN，但是应该不会使用 jsd 了。（具体解决方案后续跟进）
jsd 与去年五月份被墙，在现场。

https://github.com/jsdelivr/jsdelivr/issues/18348

![image](https://github.com/liuzhihang/halo-theme-hao/assets/79169717/a930de55-44d6-4a07-b798-fef34e7044a3)

**Comment by sun0225SUN** [comment]
一个段子，me too，me three!
![image](https://github.com/liuzhihang/halo-theme-hao/assets/79169717/8fb98f78-2333-473e-b82d-c20767230d3a)

**Comment by xyhcode** [comment]
不考虑用jsd,容易被墙

**Comment by Bytelv** [comment]
或者可以考虑一下国内的npm节点如elemecdn等等。国内有许多公益的npm节点可以使用，速度也挺快的

**Comment by Roozenlz** [comment]
@Bytelv 目前主题已经提供可选设置
![image](https://github.com/liuzhihang/halo-theme-hao/assets/93673944/b8922b28-1a06-4bd7-a412-6919974eae37)
