### ISSUE TITLE
[强烈建议]文章图片问题

### ISSUE THREAD

**Issue by Crany-web** [liuzhihang/halo-theme-hao#187]
### 你当前使用的版本

halo:2.6.0

### 描述一下此特性

在文章中使用的图片如果是包含大量代码那文章的图将毫无意义因为不放大就无法看清，但是为了看一张图专门打开一个链接就比较麻烦，因此希望主题能加入点击就放大图片的功能，多数用户写文章所用的图多为图库，希望增加一下

**Comment by sun0225SUN** [comment]
https://github.com/halo-sigs/plugin-lightgallery

**Comment by Crany-web** [comment]
十分感谢您的回答，能问一下怎么寻找图片的DOM节点，我文章中的图片是记载图库的图片(markdown语法)

**Comment by sun0225SUN** [comment]
节点我这里填的 `#post` , markdown 语法最终会被渲染成 HTML，直接右键检查即可。
![image](https://github.com/liuzhihang/halo-theme-hao/assets/79169717/6a14ed9d-eab3-4b04-a76d-10e3328f46c1)

**Comment by Crany-web** [comment]
> 节点我这里填的 `#post` , markdown 语法最终会被渲染成 HTML，直接右键检查即可。
> 
> ![image](https://user-images.githubusercontent.com/79169717/244583624-6a14ed9d-eab3-4b04-a76d-10e3328f46c1.png)

感谢老哥的解答，以解决该问题，但是我这个代码块看着好像不太对劲儿
