### ISSUE TITLE
文章页面页眉导航栏显示问题

### ISSUE THREAD

**Issue by fengxiaofeng9** [liuzhihang/halo-theme-hao#188]
### 是什么版本出现了此问题？

1.1.0

### 在线站点地址

https://blog.sunguoqi.com/

### 发生了什么？

文章详情页，页眉导航栏，没有做背景，导致与内容重叠。

### 附加信息

<img width="1003" alt="image" src="https://github.com/liuzhihang/halo-theme-hao/assets/95844852/56ddf4f7-6f28-43c3-bba9-1d1ccfdb2972">

**Comment by liuzhihang** [comment]
更新最新版本
