### ISSUE TITLE
更新后样式丢失

### ISSUE THREAD

**Issue by mobeicanyue** [liuzhihang/halo-theme-hao#192]
### 是什么版本出现了此问题？

刚刚升级的最新版

### 在线站点地址

https://blog.yoona.site/

### 发生了什么？

https://blog.yoona.site/

**Comment by liuzhihang** [comment]
…… 是不是没更新对

**Comment by mobeicanyue** [comment]
![image](https://github.com/liuzhihang/halo-theme-hao/assets/81098819/f9c2a5e4-dbcc-4104-b7f4-2b068e38646a)

![image](https://github.com/liuzhihang/halo-theme-hao/assets/81098819/c2278450-a3c0-43d1-90eb-5f912fbf41f9)
我是这样更新的
