### ISSUE TITLE
更新后底部社交网络图标显示不正常,瞬间里的图片显示半拉

### ISSUE THREAD

**Issue by git-kings** [liuzhihang/halo-theme-hao#194]
### 是什么版本出现了此问题？

1.1.2

### 在线站点地址

https://ihxx.cc

### 发生了什么？

更新完1.1.2后底部社交网络图标不显示
![image](https://github.com/liuzhihang/halo-theme-hao/assets/66518019/a42cc209-5490-46ea-b81c-4d7940d2a4da)
瞬间里边的图片显示半拉
![image](https://github.com/liuzhihang/halo-theme-hao/assets/66518019/fd1acb8c-4dd9-4bb9-bd39-f8301846f563)

**Comment by liuzhihang** [comment]
更新最新版本
