### ISSUE TITLE
友链问题

### ISSUE THREAD

**Issue by yyds67890** [liuzhihang/halo-theme-hao#195]
### 是什么版本出现了此问题？

友链无法设置

### 在线站点地址

https://ikun.at/

### 发生了什么？

友链在后台无法管理

### 相关日志输出

```shell
没有输出
```

### 附加信息

没有

**Comment by yyds67890** [comment]
博主的1.1.2

**Comment by yyds67890** [comment]
![image](https://github.com/liuzhihang/halo-theme-hao/assets/135347615/7c5c6f7f-793e-43ae-97dd-2c6d25041a9e)

**Comment by yyds67890** [comment]
![image](https://github.com/liuzhihang/halo-theme-hao/assets/135347615/1a75ce65-0236-402e-91f2-f489f756a378)

**Comment by yyds67890** [comment]
![image](https://github.com/liuzhihang/halo-theme-hao/assets/135347615/f37373ce-1110-441e-bd48-f5d7b1921e4f)

**Comment by yyds67890** [comment]
这个我在后台无法管理

**Comment by yyds67890** [comment]
还有写文章的时候最难受，一直写不上

**Comment by sun0225SUN** [comment]
![image](https://github.com/liuzhihang/halo-theme-hao/assets/79169717/77ca5ebc-c86f-4ba6-905d-98dc73017b14)
友链已被集成到侧栏，如果左侧没有链接选项，可尝试清楚Nginx服务器缓存 `/www/server/nginx/proxy_cache_dir`
