### ISSUE TITLE
文章页面无法显示

### ISSUE THREAD

**Issue by xyhcode** [liuzhihang/halo-theme-hao#208]
### 是什么版本出现了此问题？

1.1.4

### 发生了什么？

点击首页文章模块 无法跳转，直接查看文章链接显示500

<img width="506" alt="image" src="https://github.com/liuzhihang/halo-theme-hao/assets/64968400/ebb45f1a-d3a6-4183-865f-4e9dcfece44e">

**Comment by sun0225SUN** [comment]
应该是后台配置项没设置好导致的报错，可以先尝试下关掉两个赞赏按钮，即不启动赞赏功能试试。
https://blog.sunguoqi.com 我的站点是正常的

**Comment by xyhcode** [comment]
> 应该是后台配置项没有设置好导致的报错，可以先尝试下关掉两个崇拜按钮，即不启动崇拜功能尝试。 https://blog.sunguoqi.com我的站点是正常的

确实是这个问题
