### ISSUE TITLE
体验优化

### ISSUE THREAD

**Issue by sugarlesss** [liuzhihang/halo-theme-hao#211]
### 是什么版本出现了此问题？

1.1.2

### 发生了什么？

使用暗黑模式时，跳转到  友链（/links） 和 关于（about）页面，页面会闪一下（页面从浅色模式切换到深色模式），体验不太好

其他页面不会

**Comment by sun0225SUN** [comment]
看下你的站点，我的好像不存在这个问题

https://blog.sunguoqi.com

**Comment by sugarlesss** [comment]
是的，我看你站点就没这问题

帮忙看下我的，谢谢
http://106.52.60.197:8090

**Comment by sun0225SUN** [comment]
你的确实（狗头）

**Comment by sugarlesss** [comment]
阿这。。。

**Comment by sugarlesss** [comment]
补充一下：右键菜单 / 加载页 我都设置参数并启用了，但从页面效果上看 似乎也没生效

**Comment by sun0225SUN** [comment]
你 Halo 版本是多少哎 ❓

**Comment by sugarlesss** [comment]
2.6

刚装的

**Comment by sugarlesss** [comment]
升级halo至2.7，hao 1.1.5 后正常
