### ISSUE TITLE
文章评论在后台出现文章“未知”

### ISSUE THREAD

**Issue by zhangfeibiao** [liuzhihang/halo-theme-hao#229]
### 是什么版本出现了此问题？

1.1.5

### 发生了什么？

这个主题添加了一条评论，但关联的文章确实显示“未知”，其它主题正常的

<img width="712" alt="image" src="https://github.com/liuzhihang/halo-theme-hao/assets/34374831/fb04bae6-ed6b-4fa6-988e-fb5af9e227a4">

**Comment by shy-share** [comment]
@zhangfeibiao 麻烦提供下网址，可能那个人评论的时候填写的地址有问题，就会显示为未知了

**Comment by sun0225SUN** [comment]
“未知”通常出现在自定义页面（非文章页面）应该是主题没有适配评论插件。

目前主题没计划继续适配官方评论插件了，评论系统建议选择 Twikoo 系统，Twikoo评论的官方文档[点我查看](https://twikoo.js.org/)

**Comment by zhangfeibiao** [comment]
> 

应该是官方评论插件适配问题，我看下 Twikoo 系统
