### ISSUE TITLE
鱼塘开关

### ISSUE THREAD

**Issue by sugarlesss** [liuzhihang/halo-theme-hao#231]
### 你当前使用的版本

1.1.5

### 描述一下此特性

给一个开关用于控制是否启用鱼塘，目前是强制显示
<img width="1387" alt="image" src="https://github.com/liuzhihang/halo-theme-hao/assets/49931320/332ead85-90bb-46f2-bb21-a6098782725f">

**Comment by sun0225SUN** [comment]
v1.1.6 已添加此开关，在【友链鱼塘】最下面。
<img width="613" alt="image" src="https://github.com/liuzhihang/halo-theme-hao/assets/79169717/f4f83c1f-1afb-4c37-9e6c-8d93b877d1ae">
<img width="1980" alt="image" src="https://github.com/liuzhihang/halo-theme-hao/assets/79169717/ab2d78de-6dbb-4021-8813-8e9e9d20977f">
