### ISSUE TITLE
页脚代码注入失效

### ISSUE THREAD

**Issue by sugarlesss** [liuzhihang/halo-theme-hao#234]
### 是什么版本出现了此问题？

1.1.5

### 发生了什么？

页脚代码注入失效，测了好几个页面，没有把填写的代码段注入
<img width="817" alt="image" src="https://github.com/liuzhihang/halo-theme-hao/assets/49931320/f0fb6768-b963-4c1a-b7a7-b28b192b5cdc">

版本：
* halo 2.7.0
* hao 1.1.5

**Comment by shy-share** [comment]
@sugarlesss 你注入的代码是什么？麻烦贴上来 我们才可以复现问题

**Comment by sugarlesss** [comment]
> @sugarlesss 你注入的代码是什么？麻烦贴上来 我们才可以复现问题

大概是这样：
```
<script>
// todo something
</script>
```

也试过直接贴纯文本：
```plaintext
测试文本
```

禁用缓存刷新后查看网页源代码，均无效

**Comment by sun0225SUN** [comment]
可以尝试在头部注入代码，然后使用`defer` 属性 定义脚本渲染时机。
<img width="871" alt="image" src="https://github.com/liuzhihang/halo-theme-hao/assets/79169717/505c0018-f76a-4fa9-a6de-3bf5cfcb0b1d">
