### ISSUE TITLE
文章首页配图开关，文章页顶部图开关

### ISSUE THREAD

**Issue by minterjia** [liuzhihang/halo-theme-hao#236]
### 你当前使用的版本

v1.1.5

### 描述一下此特性

有图片感觉加载变慢了，请求大佬们给增加个开关

**Comment by sun0225SUN** [comment]
在这个主题中，文章封面图是博客整体设计布局的主要组成部分，当然这会带来一定的性能损耗，但不太方便增设开关，如您仍然有这方面的需求，可以尝试自定义 css 隐藏封面图，同时设计相关布局。
可参考 #230 询问他的具体做法（他已经自定义实现无封面首页了）。
