### ISSUE TITLE
Halo 2.6  Hao 1.1.5 关于页面个人信息填写后，页面报错500

### ISSUE THREAD

**Issue by Wzl1999** [liuzhihang/halo-theme-hao#237]
### 是什么版本出现了此问题？

Halo 2.6  Hao 1.1.5

### 发生了什么？

![image](https://github.com/liuzhihang/halo-theme-hao/assets/69382806/02fbdf2d-b678-4c1d-9a72-8d040f39db26)
![image](https://github.com/liuzhihang/halo-theme-hao/assets/69382806/f70905ef-2b8a-40bc-8bc0-0b7752c5129f)

**Comment by AirboZH** [comment]
这个问题现在还存在么？可以提供详细的说明么？

**Comment by Wzl1999** [comment]
在个人那里随便填写一个个人信息，点击保存后  访问关于页面，就会报500错误

**Comment by AirboZH** [comment]
收到。
已经确定了问题原因。很快会修复。
