### ISSUE TITLE
Halo 2.6  Hao 1.1.5 右上角数字不变化，一直是0

### ISSUE THREAD

**Issue by Wzl1999** [liuzhihang/halo-theme-hao#238]
### 是什么版本出现了此问题？

Halo 2.6  Hao 1.1.5

### 发生了什么？

![image](https://github.com/liuzhihang/halo-theme-hao/assets/69382806/063afa77-7c60-4cbc-8360-85d56219fbd5)

**Comment by shy-share** [comment]
@Wzl1999 麻烦提供一下你的网站地址

**Comment by Wzl1999** [comment]
http://wanzl.top/about

**Comment by shy-share** [comment]
> http://wanzl.top/about

@Wzl1999 打不开你的网站

**Comment by Wzl1999** [comment]
我重装了两边halo和主题了 都有问题,我怀疑是我系统的问题 我用Centos系统试试

**Comment by shy-share** [comment]
> 我重装了两边halo和主题了 都有问题,我怀疑是我系统的问题 我用Centos系统试试

好的 我的就是centos的系统

**Comment by shy-share** [comment]
> 试了 还是不行 地址是 http://wanzl.top 账号：admin 密码：123456 可以帮忙看看吗

@Wzl1999 可以，但是你的网站404了

**Comment by Wzl1999** [comment]
现在应该好了
