### ISSUE TITLE
侧栏 “社交媒体” 选项中无法正常添加电子邮件选项

### ISSUE THREAD

**Issue by Starsbon** [liuzhihang/halo-theme-hao#25]
### 是什么版本出现了此问题？

1.0.1

### 发生了什么？

在后台设置 侧栏 - 社交媒体 选项时，只能填写社交媒体的链接，导致没有办法填写邮箱等信息。

**Comment by liuzhihang** [comment]
这里填写的是类似QQ邮箱的邮我链接，你可以找一下你的邮箱有没有这个，仅仅填写邮箱也没法展示啊。

**Comment by Starsbon** [comment]
我以为是 mailto 协议这种的...邮我还真不太了解，我去看看~
