### ISSUE TITLE
当有二级菜单时候，白色背景下，hover的导航栏字体也会变成白色，样式就看不见文字栏。

### ISSUE THREAD

**Issue by BingoLL** [liuzhihang/halo-theme-hao#254]
### 是什么版本出现了此问题？

1.1.2和1.1.5

### 发生了什么？

当有二级菜单时候，白色背景下，hover的导航栏字体也会变成白色，样式就看不见文字栏。

**Comment by sun0225SUN** [comment]
这是由于服务器缓存导致的样式未正常加载，你看下，我的网站是正常的。
清理服务器缓存的话，如果是宝塔创建的话，会有这条目录`/www/server/nginx/proxy_cache_dir`，可以尝试清空改目录下的所有文件。

**Comment by sun0225SUN** [comment]
如您解决此问题，请给予回复，我会关闭这条 issue .

**Comment by BingoLL** [comment]
问题解决，缓存问题。
