### ISSUE TITLE
深色模式下的搜索框问题

### ISSUE THREAD

**Issue by jiuyue52** [liuzhihang/halo-theme-hao#26]
### 是什么版本出现了此问题？

1.0.1

### 在线站点地址

https://haloy.52n.cc

### 发生了什么？

深色模式下，搜索框的 字 也变成浅色的了，而搜索框本身还是浅色，导致搜索框中输入的字看不清

**Comment by liuzhihang** [comment]
搜索框使用的是插件，插件暂时不支持自定义 css，我看下如何解决
