### ISSUE TITLE
个人-个人技术栈-修改后无法正常回显示

### ISSUE THREAD

**Issue by yushui1995** [liuzhihang/halo-theme-hao#261]
### 是什么版本出现了此问题？

1.1.6

### 发生了什么？

个人-个人技术栈-修改后无法正常回显示
![image](https://github.com/liuzhihang/halo-theme-hao/assets/28134025/adeb9050-2b3c-42b7-a913-a0b168c777bb)

**Comment by sun0225SUN** [comment]
Todo
- [ ] 后台管理面板帮助信息【个人】——>【关于】
- [ ] 首页顶部 Banner 个人技术栈背景适配
- [ ] 关于页面 个人技术栈背景适配
