### ISSUE TITLE
服务器缓存导致的CSS和其他各种疑难杂症

### ISSUE THREAD

**Issue by lanbinshijie** [liuzhihang/halo-theme-hao#263]
### 是什么版本出现了此问题？

1.1.3

### 在线站点地址

https://lib.lanbin.top

### 发生了什么？

# 问题说明
本文介绍了很多由于服务器缓存导致的CSS、JS和页面预览问题。

## 临床表现
<img width="767" alt="82eb4b3c21890de12340c6ecec73cde" src="https://github.com/liuzhihang/halo-theme-hao/assets/62149873/b150c36d-670f-486b-bb8a-d011acd452e2">
<img width="326" alt="69d3246fe6946dad607f324d02ffceb" src="https://github.com/liuzhihang/halo-theme-hao/assets/62149873/a123818d-b6f6-4fbf-abaf-59f06a61edc0">

## 病因分析
其实幕后的黑手就是Nginx的缓存功能。Nginx的缓存是一种将经常请求的数据暂时存储在内存中的技术。它可以在后续请求中直接返回已缓存的数据，而无需再次访问后端服务器。Nginx的缓存功能有助于提高网站性能和响应速度，并减轻后端服务器的负载。
Nginx缓存的作用包括：
1. 提高性能：通过减少从后端服务器获取数据的次数，加快了响应时间，提升了网站的性能。
2. 减轻服务器压力：缓存可以减少对后端服务器的请求，从而降低了服务器的负载。这使得服务器能够处理更多的并发请求。
3. 改善用户体验：由于缓存可以减少网络延迟和提高响应速度，因此用户能够更快地加载页面内容，获得更好的用户体验。
4. 后端保护：当后端服务器不可用或故障时，缓存可以提供备份数据以继续为用户提供服务。这有助于确保网站的稳定性和可用性。

# 如何解决？
解决方法十分简单，办法来自小孙同学@sun0225SUN。
1. 连接上服务器或者打开宝塔面板
2. 切换到如下目录`/www/server/nginx/proxy_cache_dir`
4. 全选文件并删除
5. 重新访问网站看看效果
*(注意，这个地址一般不会改变，但是如果您有特殊设置，请前往Nginx根目录修改)*
**非宝塔用户请前往Nginx根目录修改**
<img width="1557" alt="5d6755d371fe121635d073a23b2cd9ec_" src="https://github.com/liuzhihang/halo-theme-hao/assets/62149873/78d12959-7c2b-4ae5-ac91-d03c97904260">

**Comment by AirboZH** [comment]
这个问题在静态资源文件使用npm的资源后会解决。优先使用npm的资源即可。

**Comment by lanbinshijie** [comment]
主题升级后该问题已有解决方案，故现在关闭此问题。
