### ISSUE TITLE
今日推荐 模块链接无法正常跳转

### ISSUE THREAD

**Issue by erruicoders** [liuzhihang/halo-theme-hao#264]
### 是什么版本出现了此问题？

1.1.6

### 发生了什么？

今日推荐 模块链接无法正常跳转

**Comment by lanbinshijie** [comment]
您可能需要提供更多信息我们才能更好地定位问题

**Comment by lanbinshijie** [comment]
今日推荐模块使用的是pjax跳转，目前仅支持站内链接跳转，你可以试试把你的链接改成`/about`试试

**Comment by sun0225SUN** [comment]
哈哈，我让他提的Bug。

ToDo
- [ ] 今日推荐跳转 Bug （仅支持站内跳转）
