### ISSUE TITLE
支持自定义首页右侧的背景花纹等样式

### ISSUE THREAD

**Issue by lanbinshijie** [liuzhihang/halo-theme-hao#274]
### 你当前使用的版本

1.1.6

### 描述一下此特性

Todo: 支持自定义首页右侧的背景花纹等样式（如图展示的背景🐳）
<img width="232" alt="image" src="https://github.com/liuzhihang/halo-theme-hao/assets/62149873/561b65ce-383f-46f3-8d82-0f6a67917337">

### 附加信息

其他Todos也可以直接扔到下面~❤️

**Comment by carolcoral** [comment]
1.4.4版本中增加支持个人信息背景图功能
