### ISSUE TITLE
默认评论，评论的文章类型和名称未知

### ISSUE THREAD

**Issue by ozersource** [liuzhihang/halo-theme-hao#276]
### 是什么版本出现了此问题？

1.1.6

### 发生了什么？

halo版本2.7
评论组件1.6.1
后台主题中的评论设置为默认时
任意文章的评论都会出现在所有文章的评论中，后台评论中的类型和文章显示未知，见下图
使用其它主题评论显示正常。

### 附加信息

![image-fxal](https://github.com/liuzhihang/halo-theme-hao/assets/82645186/48a9b042-fba7-4c09-88b8-c7a68971a464)

**Comment by sun0225SUN** [comment]
＃229
已有相关 issues
