### ISSUE TITLE
安装图库插件后，访问 /photos 提示 服务器错误 500

### ISSUE THREAD

**Issue by eliassama** [liuzhihang/halo-theme-hao#278]
### 是什么版本出现了此问题？

halo  2.7.0 hao 1.1.6

### 发生了什么？

我想有个地方用来展示一个图片集，我安装了图库插件，访问图库地址  /photos  显示 500 服务器错误

**Comment by sun0225SUN** [comment]
主题暂未适配 [图库](https://github.com/halo-sigs/plugin-photos) 插件，会有相应计划，尽情期待。
- [ ] 图库插件适配

**Comment by eliassama** [comment]
> 主题暂未适配 [图库](https://github.com/halo-sigs/plugin-photos) 插件，会有相应计划，尽情期待。


好的，非常期待
