### ISSUE TITLE
谷歌浏览器访问 底部备案信息栏不显示

### ISSUE THREAD

**Issue by git-kings** [liuzhihang/halo-theme-hao#280]
### 是什么版本出现了此问题？

1.1.6

### 在线站点地址

https://ihxx.cc

### 发生了什么？

# Google
![image](https://github.com/liuzhihang/halo-theme-hao/assets/66518019/63613feb-1fcf-4afb-bda6-e8eeeb72fd00)

# Microsoft Edge
![image](https://github.com/liuzhihang/halo-theme-hao/assets/66518019/248a7435-4b4d-40df-a24a-5f47b46db20f)

使用的是联想ThinkBook14笔记本

**Comment by AirboZH** [comment]
这是因为 AdGuard 等拦截插件可能会拦截id为`footer-banner`的标签
反馈这个问题之后 https://github.com/AdguardTeam/AdguardFilters/issues/141652 特定站点就可以不被拦截了
但是没办法让每个站点不被拦截，要么给这个footer的id换个名字，要么就自己加个白名单自欺欺人，反正自己能看见了

**Comment by git-kings** [comment]
果然如此,解决了&nbsp;
&nbsp;


xx
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年7月13日(星期四) 下午4:06
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [liuzhihang/halo-theme-hao] 谷歌浏览器访问 底部备案信息栏不显示 (Issue #280)





 
这是因为 AdGuard 等拦截插件可能会拦截id为footer-banner的标签
 反馈这个问题之后 AdguardTeam/AdguardFilters#141652 特定站点就可以不被拦截了
 但是没办法让每个站点不被拦截，要么给这个footer的id换个名字，要么就自己加个白名单自欺欺人，反正自己能看见了
 
&mdash;

**Comment by git-kings** [comment]
> 我的 Chrome 表示没问题
> 
> ![图像](https://user-images.githubusercontent.com/79169717/253199069-234bbbd9-30a8-45fa-bdaa-b2b6cb745d7f.png)

原来是我的拦截广告插件错误拦截了
