### ISSUE TITLE
菜单栏显示

### ISSUE THREAD

**Issue by RealKiro** [liuzhihang/halo-theme-hao#294]
### 是什么版本出现了此问题？

1.2.0

### 在线站点地址

https://halo.aino.fun/

### 发生了什么？

1. 我当前使用的菜单栏包含多个一级菜单，还有三级菜单，无法全部显示，也无法正常多级展开（下图为Dream主题可正常展开效果）
![image](https://github.com/liuzhihang/halo-theme-hao/assets/33367701/2e7dc714-9645-45a7-803c-e784b7d1b544)

2. 菜单栏显示不全
![image](https://github.com/liuzhihang/halo-theme-hao/assets/33367701/b37c6674-2ff2-4ca3-802f-38432e4e888c)

3. 菜单栏字体大小排列需要优化（图为电脑屏幕打开效果）
![image](https://github.com/liuzhihang/halo-theme-hao/assets/33367701/3108d822-8d91-448f-8b21-0ce8adfd13ef)

**Comment by chengzhongxue** [comment]
后续适配

**Comment by Roozenlz** [comment]
已适配，下个版本更新
