### ISSUE TITLE
侧栏-公众号自定义

### ISSUE THREAD

**Issue by RealKiro** [liuzhihang/halo-theme-hao#295]
### 你当前使用的版本

1.2.0

### 描述一下此特性

对于没有公众号需求的，能否修改自定义图片尺寸，用来放置赞赏二维码图之类的其它图片？
![image](https://github.com/liuzhihang/halo-theme-hao/assets/33367701/dd198099-1476-4c13-87cf-fef2b7c39fae)

另外：侧栏的logo图像在哪里修改？
我之前halo1.x用的这个主题，感觉挺好看的，能不能借鉴下 ？
https://bbchin.com/
https://github.com/qinhua/halo-theme-joe2.0

**Comment by liuzhihang** [comment]
可以试着放入其他图片，或者关闭这个卡片。
