### ISSUE TITLE
主页站点名左侧使用{自定义菜单}图标显示错误

### ISSUE THREAD

**Issue by git-kings** [liuzhihang/halo-theme-hao#298]
### 是什么版本出现了此问题？

1.2.0

### 在线站点地址

https://ihxx.cc

### 发生了什么？

![image](https://github.com/liuzhihang/halo-theme-hao/assets/66518019/85511da6-f4a7-4ffd-ab10-8338a6a2e347)

**Comment by chengzhongxue** [comment]
你换到图片我看看什么情况

**Comment by git-kings** [comment]
> 你换到图片我看看什么情况

可能是我的用法错了，我设置的这里显示的是主菜单，主菜单设置的是icon code（所以显示图标错误了），我换成了页脚菜单，然后设置的图片图标路径是正常的
