### ISSUE TITLE
prism.js代码高亮插件显示问题

### ISSUE THREAD

**Issue by WekyJay** [liuzhihang/halo-theme-hao#299]
### 是什么版本出现了此问题？

2.7.0 + 最新版本 theme-hao 1.2.0

### 在线站点地址

https://www.wekyjay.cn/

### 发生了什么？
一直存在的问题，代码块有时候显示有时候不显示。行号是从来不显示的，且css加载速度很慢。

![image](https://github.com/liuzhihang/halo-theme-hao/assets/20734333/993b479a-343b-4856-b4a1-6f05a50cbaf6)

**Comment by chengzhongxue** [comment]
你站有缓存问题，建议先清除下缓存

**Comment by chengzhongxue** [comment]
![image](https://github.com/liuzhihang/halo-theme-hao/assets/89380218/94805d0b-5e08-49e4-83bc-9129e9f62748)
这个是你自己加的？，1.2没有

**Comment by WekyJay** [comment]
> ![image](https://user-images.githubusercontent.com/89380218/255065049-94805d0b-5e08-49e4-83bc-9129e9f62748.png) 这个是你自己加的？，1.2没有

这个不是我自己加的

**Comment by chengzhongxue** [comment]
那你服务器缓存没有清

**Comment by WekyJay** [comment]
我试试

**Comment by chengzhongxue** [comment]
或者建议使用
![image](https://github.com/liuzhihang/halo-theme-hao/assets/89380218/f509fdae-6e42-4a3a-9967-5c2a10628650)
就不会有缓存问题

**Comment by WekyJay** [comment]
有了，谢谢大佬！
