### ISSUE TITLE
代码块auto时渲染问题

### ISSUE THREAD

**Issue by xyhcode** [liuzhihang/halo-theme-hao#30]
### 是什么版本出现了此问题？

1.0.2

### 发生了什么？

当代码块在富文本中没有指定是哪种语言时前台渲染的不是代码块：图1-图2，指定语言时就不会：图3-图4
官方主题在代码块为auto时显示图5

### 附加信息

<img width="936" alt="图1" src="https://user-images.githubusercontent.com/64968400/207038067-6e7a9b76-4cee-4e47-80fa-480d287abc4c.png">
<img width="893" alt="图2" src="https://user-images.githubusercontent.com/64968400/207038174-a13c265c-ece4-4c04-9454-867e166c0ac3.png">
<img width="821" alt="图3" src="https://user-images.githubusercontent.com/64968400/207038289-ad5d7175-3b02-46ce-9f29-94b87bf3645e.png">
<img width="836" alt="图4" src="https://user-images.githubusercontent.com/64968400/207038818-b1b9cabf-844b-4248-bc78-2938de19ac36.png">
<img width="852" alt="图5" src="https://user-images.githubusercontent.com/64968400/207038589-4a1d8337-056c-4057-8d8c-f8058a20ed7a.png">

**Comment by liuzhihang** [comment]
是使用的高亮插件么？

**Comment by liuzhihang** [comment]
see https://github.com/liuzhihang/plugin-prismjs/releases/tag/v1.0.1
