### ISSUE TITLE
halo2.7安装1.2.0主题“服务器内部错误”

### ISSUE THREAD

**Issue by zhajianjun** [liuzhihang/halo-theme-hao#300]
### 是什么版本出现了此问题？

页面无法正常显示

### 发生了什么？

halo版本：2.7
主题版本：1.2.0
问题：500 服务器错误
![image](https://github.com/liuzhihang/halo-theme-hao/assets/40648630/9dfa6969-31d6-471c-a8bd-0d8f3cf2394d)

### 相关日志输出

![image](https://github.com/liuzhihang/halo-theme-hao/assets/40648630/faab220a-3725-42df-919e-235e74b550ae)

**Comment by laiqinghua** [comment]
meto

**Comment by laiqinghua** [comment]
metoo

**Comment by zhangfeibiao** [comment]
me too !

**Comment by zhangfeibiao** [comment]
https://github.com/liuzhihang/halo-theme-hao/issues/271

**Comment by zhajianjun** [comment]
解决方式就是主题的每个设置都要保存一下就没问题了。
