### ISSUE TITLE
留言板图片是写死的吗？

### ISSUE THREAD

**Issue by zhangfeibiao** [liuzhihang/halo-theme-hao#307]
### 是什么版本出现了此问题？

v1.2.0

### 在线站点地址

http://blog.zhangfeibiao.com

### 发生了什么？

留言板的图片貌似写死的

<img width="700" alt="image" src="https://github.com/liuzhihang/halo-theme-hao/assets/34374831/a7db4dd9-3bd2-4167-83ce-f67923ed6ecd">

**Comment by chengzhongxue** [comment]
配置文件可以换
![image](https://github.com/liuzhihang/halo-theme-hao/assets/89380218/12f5bac7-a8f7-460c-aedb-40c5d071e804)

**Comment by zhangfeibiao** [comment]
主题设置在留言板默认配置的图片并不是上方的骷颅头，我试了下要改一下内容再保存才会生效，已解决。
