### ISSUE TITLE
使用百度统计代码提示referrer被警用

### ISSUE THREAD

**Issue by MDQ0512** [liuzhihang/halo-theme-hao#31]
### 是什么版本出现了此问题？

2.0

### 在线站点地址

https://www.mengorg.cn/

### 发生了什么？

使用百度统计代码提示referrer被警用
即使添加了提下5种代码均是无法使用
`1、None：绝不允许referrer data通过
标签写法：<meta name="referrer" content="none">

2、None When Downgrade：发送referrer信息去安全的HTTPS站点，而非不稳定的HTTP站点。
标签写法：<meta name="referrer" content="none-when-downgrade">

3、Origin Only: 发送协议、主机和端口（即子域）没有一个完整的URL作为来源，
即https://moz.com/example.html只会发送https://moz.com
标签写法：<meta name="referrer" content="origin">

4、Origin When Cross-Origin: 当传origin-only来路信息发送给外部站点时，如果目标有相同的协议、主机和端口（即子域），无论它是HTTP或HTTPS，都将全部的URL作为Referrer发送出去。（注解：官方说明书上有一处排印错误，将来的版本应该是"origin-when-cross-origin"）
标签写法：<meta name="referrer" content="origin-when-crossorigin">

5、Unsafe URL: 总是将URL字串作为一个referrer通过。
注意：如果你的URL中存在任何敏感信息，这不是最安全的选择。其中URL的片段、用户名、密码被自动剥去。
标签写法：<meta name="referrer" content="unsafe-url">`

**Comment by liuzhihang** [comment]
那这里应该不是主题的问题吧，应该是 halo 的问题，主题没有提供这个功能呀

**Comment by liuzhihang** [comment]
可以加群讨论下，主题的问题欢迎随时反馈。
