### ISSUE TITLE
为什么一启用Hao博客报错500?

### ISSUE THREAD

**Issue by MengHanLOVE1027** [liuzhihang/halo-theme-hao#320]
### 是什么版本出现了此问题？

v1.2.0

### 在线站点地址

https://heyuhan.v6.army

### 发生了什么？

使用的是Windows Docker容器搭建的Halo v2.7.0（今天才搞好），然后就看中了这个主题，我从Releases下载的，从本地上传安装完毕并启用之后，就报错500，是我其他的设置没做好吗？默认的主题和其他的主题是可以用的捏

### 相关日志输出

```shell
500
服务器内部错误
服务器内部发生错误，请稍候再试。
```

**Comment by Roozenlz** [comment]
在主题设置那里把所有的配置都保存一下

**Comment by MengHanLOVE1027** [comment]
> 在主题设置那里把所有的配置都保存一下

OK了谢谢帮助
