### ISSUE TITLE
【500错误】出现500错误页面后的返回首页跳转地址错误

### ISSUE THREAD

**Issue by carolcoral** [liuzhihang/halo-theme-hao#324]
### 是什么版本出现了此问题？

1.2.0

### 在线站点地址

https://carolcoral.synology.me:18083

### 发生了什么？

点击“首页”跳转的是localhost地址，而不是实际上的访问地址

### 附加信息

<img width="1638" alt="image" src="https://github.com/liuzhihang/halo-theme-hao/assets/8952687/15921111-3248-48a0-a613-ef1cb04a06c4">
<img width="1656" alt="image" src="https://github.com/liuzhihang/halo-theme-hao/assets/8952687/33c9dcbb-fbaa-4213-9611-a87052c7b0ea">

**Comment by chengzhongxue** [comment]
不是好的？

**Comment by gss196824** [comment]
![image](https://github.com/liuzhihang/halo-theme-hao/assets/58241203/7c600253-daa5-483d-a672-02f995f6daa7)


![image](https://github.com/liuzhihang/halo-theme-hao/assets/58241203/5c354c02-6823-4231-aa58-bfa3daceef8f)

![image](https://github.com/liuzhihang/halo-theme-hao/assets/58241203/be4c6b4f-60d8-4e0d-92ac-668b20348910)


新主题通过插件部署的时候，打开首页报错服务器500

**Comment by squirrelmedia** [comment]
请问您是如何解决的？我也又到了相同的情况

**Comment by liuzhihang** [comment]
> https://carolcoral.synology.me:18083

@squirrelmedia  后台设置都保存一下

**Comment by squirrelmedia** [comment]
> 

万分感谢！
