### ISSUE TITLE
随机封面修改为二次元随机图地址导致文章的”动态主色“失效

### ISSUE THREAD

**Issue by zhajianjun** [liuzhihang/halo-theme-hao#326]
### 是什么版本出现了此问题？

1.2.0

### 在线站点地址

http://www.ticho.top

### 发生了什么？

![image](https://github.com/liuzhihang/halo-theme-hao/assets/40648630/34275309-8b60-49e8-9e43-a50b4382fed5)

**Comment by chengzhongxue** [comment]
随机图片目前解决不了

**Comment by zhajianjun** [comment]
😭
