### ISSUE TITLE
【显示中控台】页面顶部”显示中控台“按钮无法限制标签数量

### ISSUE THREAD

**Issue by carolcoral** [liuzhihang/halo-theme-hao#327]
### 是什么版本出现了此问题？

1.2.0

### 在线站点地址

http://blog.cnkj.site

### 发生了什么？

页面顶部”显示中控台“按钮无法限制标签数量导致页面高度和大小被撑爆了

### 附加信息

<img width="1620" alt="image" src="https://github.com/liuzhihang/halo-theme-hao/assets/8952687/e3940aad-8433-4647-89d3-c408a424c1e2">
<img width="1386" alt="image" src="https://github.com/liuzhihang/halo-theme-hao/assets/8952687/a7183826-03ce-468b-914a-78c31531b2ca">

**Comment by chengzhongxue** [comment]
下个版本修复

**Comment by chengzhongxue** [comment]
已修复
