### ISSUE TITLE
打开页面太慢了。。。

### ISSUE THREAD

**Issue by devzwy** [liuzhihang/halo-theme-hao#328]
### 是什么版本出现了此问题？

 1.2.0

### 在线站点地址

https://www.fr71.com

### 发生了什么？

首页刷新一下渲染出来要5秒左右，我配置了cdn加速也是不行。换了官方自带的主题是ok的。但是debug调试没有发现慢的请求。不知道哪里的问题。

**Comment by Roozenlz** [comment]
这个跟主题没关系哈，不信你看我的https://roozen.top/

**Comment by devzwy** [comment]
是外接mysql引起的，打扰了
