### ISSUE TITLE
代码块Bug

### ISSUE THREAD

**Issue by TopxData** [liuzhihang/halo-theme-hao#33]
### 是什么版本出现了此问题？

1.0.2

### 发生了什么？

代码块超出文章区域

**Comment by liuzhihang** [comment]
有截图么？

**Comment by xyhcode** [comment]
确实有这个问题

**Comment by xyhcode** [comment]
当文章的代码块为auto时就会出现这个问题。
解决方案：
下载并安装代码高亮插件 [代码高亮插件](https://github.com/liuzhihang/plugin-prismjs)  开启自动识别代码块语言
<img width="576" alt="image" src="https://user-images.githubusercontent.com/64968400/207604209-b14870ae-13bd-4da6-a33d-c8b9548c95dd.png">
