### ISSUE TITLE
关于文章设置的版权样式

### ISSUE THREAD

**Issue by MengHanLOVE1027** [liuzhihang/halo-theme-hao#353]
### 是什么版本出现了此问题？

v1.3.0

### 在线站点地址

https://heyuhan.najiang.top/archives/ge-ren-xiang-mu

### 发生了什么？

1. 设置“版权样式”为“样式一”时，就出现问题了，保存了很多次，切换了很多次，只有默认样式是好的
2. 还有文章部分的引导目录那里点击引导后跳转的并不是准确的地方，而是差了那么一点距离，强迫症表示很........

这是后台设置的图片[https://img1.imgtp.com/2023/08/02/MNhaXNWy.jpg](url)

**Comment by chengzhongxue** [comment]
缓存问题

**Comment by MengHanLOVE1027** [comment]
> 缓存问题

怎么解决捏？~

**Comment by MengHanLOVE1027** [comment]
> ![image](https://user-images.githubusercontent.com/89380218/257840586-53bb3a60-9c80-4192-a48d-a89e1c72484a.png)

我去真的好了诶，谢谢~
请问一下如果说附件删除以后访问的话那个附件还是存在的是怎么解决的呢？
