### ISSUE TITLE
主题应用问题

### ISSUE THREAD

**Issue by xiaopengzzc** [liuzhihang/halo-theme-hao#358]
### 是什么版本出现了此问题？

2.8.0

### 发生了什么？

在切换到这个主题的时候，就会出现以下图所示，求解
![image](https://github.com/liuzhihang/halo-theme-hao/assets/136769452/411e7da9-8d56-4d68-ad6c-066717470aac)

**Comment by Roozenlz** [comment]
1.将主题所有配置项保存一遍
2.检查是否填写入站时间

注意查看主题的介绍以及更新说明
PLEASE!!!!

**Comment by xiaopengzzc** [comment]
已解决
