### ISSUE TITLE
文章内字体、表格优化

### ISSUE THREAD

**Issue by Jimecc** [liuzhihang/halo-theme-hao#36]
### 你当前使用的版本

2.0.1

### 描述一下此特性

# 问题
使用该主题的情况下，首页十分美观！十分喜欢！
但是文章内部的字体感觉偏大，且字体比较统一，难以区分，希望可以增加自定义字体的功能，或者将文章内部字体做一些区分，另外还可以做一些优化，比如1级标题后可以加一个分割线，这样的美化。
而且，表格很丑，有点丑，目前已经开始使用此主题，希望越做越好！

### 附加信息

[【博客】](http://blog.sahry.cc)

**Comment by Jimecc** [comment]
博客地址写错了，点击这里 http://blog.shary.cc

**Comment by liuzhihang** [comment]
后面会做

**Comment by sun0225SUN** [comment]
目前可以通过后台嵌入自定义的 css 样式来实现你的需求。
（这块粒度比较细，可能很久才会完善到出具体配置项）

![image](https://github.com/liuzhihang/halo-theme-hao/assets/79169717/9556246a-986b-40ae-aaf0-9a3cc84fdea4)
