### ISSUE TITLE
友链朋友圈无法获取文章

### ISSUE THREAD

**Issue by Bytelv** [liuzhihang/halo-theme-hao#364]
### 是什么版本出现了此问题？

1.3.0

### 在线站点地址

http://blog.lvbyte.top/fcircle

### 发生了什么？

当我点开这个网址时，无法获取友链文章
显示错误信息为： NetWork Error

### 附加信息

我在后台设置中 [友链鱼塘] -> [token地址]，设置的值为： https://cdn.jsdelivr.net/gh/Bytelv/hexo-circle-of-friends@main/data.json
如果需要正常运行的话，我需要怎么配置token地址？
友链朋友圈应如何配置，才能抓取 https://blog.lvbyte.top/links 的友链，并自动抓取文章？

**Comment by Roozenlz** [comment]
需要你部署一个友链朋友圈的服务，提供一个url地址，静态文件不支持

**Comment by Bytelv** [comment]
> 需要你部署一个友链朋友圈的服务，提供一个url地址，静态文件不支持

LINK:
    - {link: "https://www.yyyzyyyz.cn/link/", theme: "butterfly"}  # link改为你的友链页地址，theme选择你的博客主题

那这个该如何填？（theme）

**Comment by Roozenlz** [comment]
token填写这个即可，注意最后面要有斜杠
https://friend.lvbyte.tk/
