### ISSUE TITLE
文章详情中 评论模块的注销按钮可以去除 否则任何人都可以进行注销

### ISSUE THREAD

**Issue by 2332810801** [liuzhihang/halo-theme-hao#37]
### 是什么版本出现了此问题？

halo2.0.1 theme 1.0.3

### 发生了什么？

文章详情中 评论模块的注销按钮可以去除 否则任何人都可以进行注销

**Comment by liuzhihang** [comment]
这个你应该提给插件，让插件支持更多自定义 css，现在仅仅是引入了插件，没有做任何定制。
