### ISSUE TITLE
出现 500 服务器内部出现问题

### ISSUE THREAD

**Issue by PKU-Fgx** [liuzhihang/halo-theme-hao#371]
### 是什么版本出现了此问题？

Hao 1.3.1

### 在线站点地址

fanggx.xyz

### 发生了什么？

打开之后出现问题：
![image](https://github.com/liuzhihang/halo-theme-hao/assets/109190471/8f9e9236-bf8d-47cb-b403-a53894a847fb)
点首页返回后提示：
![image](https://github.com/liuzhihang/halo-theme-hao/assets/109190471/a5b7aa6b-36a7-4414-9ef3-99640ebee119)

**Comment by Roozenlz** [comment]
首页报错500请你仔细看主题说明和更新说明。。。。
点击首页跳转的链接你填的是localhost。。。。
