### ISSUE TITLE
明暗切换无效、Banner 左侧标题设置后显示不全、BANNER 右侧今日推荐手机端不显示、

### ISSUE THREAD

**Issue by eliassama** [liuzhihang/halo-theme-hao#372]
### 是什么版本出现了此问题？

1.3.1

### 发生了什么？

一：
明暗切换无效。报错：
<img width="874" alt="image" src="https://github.com/liuzhihang/halo-theme-hao/assets/79587688/4ee66655-1611-42ce-a79a-4df715bdc4f3">

---
二：
主题设置 - 顶部 - Banner 左侧 - 标题 （就是最少有三个的那个）
<img width="765" alt="image" src="https://github.com/liuzhihang/halo-theme-hao/assets/79587688/538a0064-8249-43ef-8b95-9371b961f025">
手机端只显示两个
![image](https://github.com/liuzhihang/halo-theme-hao/assets/79587688/803f73bb-cfc9-4f65-90c9-523b64e63837)

---
三：
主题设置 - 顶部 - Banner 右侧 - 今日推荐。在电脑端显示手机端不显示

**Comment by eliassama** [comment]
问题一：已解决。把所有的东西都保存一遍

**Comment by sun0225SUN** [comment]
剩下两个问题。。。

前端本来就是这么设计的。。。

主题样式参考：https://blog.zhheo.com

如何你有更好的设计方案，欢迎PR。
