### ISSUE TITLE
启动不了

### ISSUE THREAD

**Issue by smallmayi** [liuzhihang/halo-theme-hao#38]
### 是什么版本出现了此问题？

halo2.0.1  hao1.0.3

### 发生了什么？

![image](https://user-images.githubusercontent.com/42774709/207820183-f80f78f8-13c3-4d79-b72d-06facfbffed5.png)
切换主题报错了

### 附加信息

![image](https://user-images.githubusercontent.com/42774709/207824170-833cc0da-0c51-47ae-81c4-910969b7b158.png)

**Comment by liuzhihang** [comment]
打开主题，任意地方点下保存。这不是主题的问题，是 halo 没有给生成 configMap

**Comment by smallmayi** [comment]
> 

thanks
