### ISSUE TITLE
设置中未开启404却新建了对应页面导致的格式错误

### ISSUE THREAD

**Issue by lanbinshijie** [liuzhihang/halo-theme-hao#387]
### 是什么版本出现了此问题？

1.1.6

## 提示
好像在第一次设置完404页面后关闭404页面对应效果也不会变化了。应该是主题404对应设置为空时启用（或创建）了404页面显示效果就会出现问题。

## 问题猜测
可能是设置中404的启动和关闭没有实质性的效果，只要创建了对应页面就能够访问404，无论是否在设置中开启。所以如果第一次没有在设置中填写404栏目就会导致显示的bug。

### 附加BUG
默认的提示图片无法正常访问。

## 解决方案
1. 取消`主题设置-404`中的启用和禁用按钮
2. 重新设置默认404提示词和提示图片
3. （可能还要更新一下404的整个界面）

正确样式：
![image](https://github.com/liuzhihang/halo-theme-hao/assets/62149873/ccf058ad-d7c0-42c2-892b-79e7ce2352bf)

设置后：
<img width="446" alt="image" src="https://github.com/liuzhihang/halo-theme-hao/assets/62149873/e0cc97c5-bef4-40ba-b6ab-49b914b40fdd">

<img width="655" alt="image" src="https://github.com/liuzhihang/halo-theme-hao/assets/62149873/b625d736-99ac-46ea-b06e-f151897116a1">

**Comment by chengzhongxue** [comment]
![image](https://github.com/liuzhihang/halo-theme-hao/assets/89380218/6e108a6e-ef82-4417-9883-99c225cccbb4)
你版本有问题，而且1.3也没有这个问题，1.2我就移除了这个配置

**Comment by lanbinshijie** [comment]
经过排查应该是升级后没有重载主题配置。正常升级并承载主题配置和问题可以解决。
