### ISSUE TITLE
文章界面右上角进度条一直为零0

### ISSUE THREAD

**Issue by Pollen-Z** [liuzhihang/halo-theme-hao#414]
### 是什么版本出现了此问题？

2.8.0

### 发生了什么？

文章界面右上角进度条一直为零0
![image](https://github.com/liuzhihang/halo-theme-hao/assets/98813410/a78beead-438a-40ff-9e26-a3410ecdee0a)

**Comment by Pollen-Z** [comment]
好像不只是文章界面，主页的也是0
![image](https://github.com/liuzhihang/halo-theme-hao/assets/98813410/bb861dee-cdfd-431b-ad62-c51d599dccf2)

**Comment by Roozenlz** [comment]
第一步，刷新浏览器的缓存

**Comment by Pollen-Z** [comment]
> 



> 
大佬，是这个吗？
![image](https://github.com/liuzhihang/halo-theme-hao/assets/98813410/74511ea4-dbe8-4095-8f1c-a00062653ac4)

**Comment by Pollen-Z** [comment]
已解决！！！

**Comment by Pollen-Z** [comment]
备份后重装了一下Halo-Docker，就好了！感谢！！！
