### ISSUE TITLE
关于侧栏目录定位问题

### ISSUE THREAD

**Issue by MengHanLOVE1027** [liuzhihang/halo-theme-hao#416]
### 是什么版本出现了此问题？

v1.3.2

### 在线站点地址

https://heyuhan.dns.navy/archives/ge-ren-li-shi

### 发生了什么？

点击定位时，滚动到了页面的最开始的地方（也就是导航栏那里），被导航栏覆盖了，请问有什么办法修复呢？
我还安装了 Tocbot V1.0.0版本，自定义配置如下
`tocSelector: '.toc-content',
contentSelector: '.post-content',
headingSelector: 'h1, h2, h3, h4, h5,h6',
positionFixedSelector: ".toc-content", 
scrollEndCallback: function (e) {
  //修正滚动后页面的位置，80 是自己顶部栏的高度 
  window.scrollTo(window.scrollX, window.scrollY - 1000
);`
但是似乎没作用捏QAQ

**Comment by liushiquan1234** [comment]
我在v1.4.3版本遇到了同样的问题(https://blog.liusq.top),我需要怎么修复它?
