### ISSUE TITLE
代码块无一键复制按钮

### ISSUE THREAD

**Issue by wdmJieyao** [liuzhihang/halo-theme-hao#417]
### 是什么版本出现了此问题？

3.1.2

### 在线站点地址

https://www.hzaw.org/

### 发生了什么？

![image](https://github.com/liuzhihang/halo-theme-hao/assets/47850366/f90766d3-fcb5-4cbd-8d1d-9525e9c752ea)

代码块无法复制，控制台无报错

**Comment by MengHanLOVE1027** [comment]
![image](https://github.com/liuzhihang/halo-theme-hao/assets/99132833/2068e11d-8683-4105-99e3-70f2463628a7)
这不有吗？
