### ISSUE TITLE
支持文章显示作者信息

### ISSUE THREAD

**Issue by ZhangHuan95** [liuzhihang/halo-theme-hao#419]
### 你当前使用的版本

1.3.2

### 描述一下此特性

由于站点有多人维护，希望在标题栏下方，显示当前文章的作者。

**Comment by chengzhongxue** [comment]
@ZhangHuan95 
看下能不能给个参考，添加位置

**Comment by ZhangHuan95** [comment]
> @ZhangHuan95 看下能不能给个参考，添加位置
![image](https://github.com/liuzhihang/halo-theme-hao/assets/26647010/9f2ba204-8143-4365-86d8-14be85d92195)
这样就行！

**Comment by chengzhongxue** [comment]
@ZhangHuan95 
![image](https://github.com/liuzhihang/halo-theme-hao/assets/89380218/32154fc3-a652-4291-b8ea-5f644c06413d)
