### ISSUE TITLE
删除主菜单后首页直接500了

### ISSUE THREAD

**Issue by FnTop** [liuzhihang/halo-theme-hao#424]
### 是什么版本出现了此问题？

halo2.8

### 发生了什么？

删除后台默认的菜单项后直接500了

### 附加信息

![image](https://github.com/liuzhihang/halo-theme-hao/assets/43026579/e669d099-a227-44dd-b2c8-08d7a79210b0)
![image](https://github.com/liuzhihang/halo-theme-hao/assets/43026579/c239566a-b4e5-4c3a-ab99-a3104775eee5)

**Comment by chengzhongxue** [comment]
不懂就问，你主菜单都删掉了，你觉得会不会直接500

**Comment by lanbinshijie** [comment]
不懂就问，一本字典删掉了目录该怎么看呢？
