### ISSUE TITLE
图库查看大图一直是加载中

### ISSUE THREAD

**Issue by LiberatorHg** [liuzhihang/halo-theme-hao#425]
### 是什么版本出现了此问题？

1.3.3

### 发生了什么？

图库，查看大图，一直懒加载中

已重新删了又加，换了2个浏览器也是

### 附加信息

![image](https://github.com/liuzhihang/halo-theme-hao/assets/52238701/ba7f8f4a-0eb3-4465-838e-810d30977dca)

**Comment by chengzhongxue** [comment]
懒加载插件关掉，有问题

**Comment by LiberatorHg** [comment]
> 懒加载插件关掉，有问题

可以了！！感谢你
