### ISSUE TITLE
添加文章点赞功能

### ISSUE THREAD

**Issue by lanbinshijie** [liuzhihang/halo-theme-hao#429]
### 你当前使用的版本

1.3.3

### 描述一下此特性

在每篇文章下方添加点赞按钮和显示当前点赞数，限制同一个IP的点赞数量，允许游客点赞，点赞后有动效。

（开坑）

**Comment by Roozenlz** [comment]
问题是数据存哪，目前好像不是很方便实现

**Comment by lanbinshijie** [comment]
> 问题是数据存哪，目前好像不是很方便实现

是不是可以给文章添加一个元数据？当做文章属性的一个，用JS给每个设备添加一个唯一识别码，存储点赞过的识别码，显示的时候统计总数？

**Comment by carolcoral** [comment]
主题目前是纯前端实现，点赞需要后端进行配合保存数据和判断IP来源，目前暂时无法实现，建议去halo官方[ISSUES](https://github.com/halo-dev/halo/issues)提交该需求
