### ISSUE TITLE
icon无法显示

### ISSUE THREAD

**Issue by luckyEason** [liuzhihang/halo-theme-hao#434]
### 是什么版本出现了此问题？

1.3.2

### 在线站点地址

https://blog.fishhome.link

### 发生了什么？

icon无法显示
![image](https://github.com/liuzhihang/halo-theme-hao/assets/109937362/9e9aa5db-9167-43b3-8d73-23577ac708a2)

### 附加信息

![image](https://github.com/liuzhihang/halo-theme-hao/assets/109937362/4d6810c8-82ac-48b6-b952-c188e5bfee99)

**Comment by Karlvision** [comment]
一样的问题，之前好好的

**Comment by chengzhongxue** [comment]
请更新主题，之前的图标挂了
