### ISSUE TITLE
[建议]文章中的代码块跟换样式

### ISSUE THREAD

**Issue by Crany-web** [liuzhihang/halo-theme-hao#437]
### 你当前使用的版本

halo:2.8.0

### 描述一下此特性

建议将主题的代码块换成https://arch.icekylin.online/guide/advanced/optional-cfg-2.html 里边的代码块

**Comment by Roozenlz** [comment]
![image](https://github.com/liuzhihang/halo-theme-hao/assets/93673944/34c976ca-76c3-4ca0-9585-5f935abc7a47)
你是想要这个功能吗

**Comment by chengzhongxue** [comment]
建议可以，但是不一定实现

**Comment by Crany-web** [comment]
> ![image](https://user-images.githubusercontent.com/93673944/262043384-34c976ca-76c3-4ca0-9585-5f935abc7a47.png) 你是想要这个功能吗

是的是的，感觉这种代码块有时候比较好用

**Comment by chengzhongxue** [comment]
目前实现不了

**Comment by Crany-web** [comment]
> 目前实现不了

十分感谢师傅的回复，这种代码块或许只有我觉得比较好用，当然师傅的主题是蛮好用的，还有个小疑惑，不知道是不是我设置的问题，主题的代码块好像没有复制功能

**Comment by chengzhongxue** [comment]
@Crany-web 截图看看，然后站点放出来看看

**Comment by Crany-web** [comment]
> @Crany-web 截图看看，然后站点放出来看看

站点：https://arch.icekylin.online/guide/advanced/optional-cfg-2.html
站点代码块样式：
![1.png](http://img.crany.fun/i/2023/09/23/650ea4c678e19.png)
![2.png](http://img.crany.fun/i/2023/09/23/650ea4c6b7f1f.png)
![3.png](http://img.crany.fun/i/2023/09/23/650ea4c7123e3.png)
