### ISSUE TITLE
加载模块图片是不是样式出现了问题

### ISSUE THREAD

**Issue by OPMonday** [liuzhihang/halo-theme-hao#44]
### 是什么版本出现了此问题？

1.0.4

### 在线站点地址

https://monyun.top/

### 发生了什么？

![image](https://user-images.githubusercontent.com/105340869/209432143-1079ecbb-600e-42f0-9860-cdc3a61ca7e0.png)
![image](https://user-images.githubusercontent.com/105340869/209432186-bf50d671-1060-4144-9fcd-32cbd39230f3.png)

**Comment by liuzhihang** [comment]
我看下哈
