### ISSUE TITLE
Head 信息 增加封面图

### ISSUE THREAD

**Issue by LiuOcean** [liuzhihang/halo-theme-hao#449]
### 你当前使用的版本

1.3.4

### 描述一下此特性

封面图在社交分享时的自动抓取还是失效的，目前默认抓取的是正文的第一张图片

![image](https://github.com/liuzhihang/halo-theme-hao/assets/20659474/b89e5c99-c474-4c58-9685-0e26fc5d2c0b)

[相关内容](https://github.com/liuzhihang/halo-theme-hao/issues/436)

**Comment by carolcoral** [comment]
下个版本计划增加

**Comment by carolcoral** [comment]
经过核对，目前无法实现预期效果（bing、baidu等搜索引擎的抓取图显示）
