### ISSUE TITLE
设置成”默认浅色，允许用户自己切换“后无效，依旧是跟随系统（目前是黑色）

### ISSUE THREAD

**Issue by Jimecc** [liuzhihang/halo-theme-hao#45]
### 是什么版本出现了此问题？

1.0.4

### 在线站点地址

http://blog.shary.cc

### 发生了什么？

# 问题描述
在主题设置界面-样式界面做出如下这是，但是界面还是黑色（跟随系统），且我没找到切换颜色的按钮在哪里。
<img width="625" alt="Jim's_2022-12-30 18 55 24" src="https://user-images.githubusercontent.com/41030702/210062746-f416d736-da2b-433a-ac75-6ee151ac031d.png">

### 相关日志输出

```shell
无
```

### 附加信息

无

**Comment by AirboZH** [comment]
您可以更新一下主题看这个问题是否还存在。另外，目前的切换是在主题的右键菜单中

**Comment by AirboZH** [comment]
没有复现，作者没有后续跟进
