### ISSUE TITLE
顶部部分内容无法显示

### ISSUE THREAD

**Issue by RicharPao** [liuzhihang/halo-theme-hao#455]
### 是什么版本出现了此问题？

1.3.3

### 在线站点地址

https://blog.vacuole.top

### 发生了什么？

在后台的顶部设置中，打开了技术栈、banner、今日推荐等模块，但是在实际的顶部中还是没有，我看几个Demo也没有，是不是还没有实装这个功能？
还有，实用教程分类在页面中不显示，只有前两个

**Comment by chengzhongxue** [comment]
![Uploading image.png…]()
这不是有？

**Comment by chengzhongxue** [comment]
![image](https://github.com/liuzhihang/halo-theme-hao/assets/89380218/c662a0af-c905-4a0c-b0b5-907479f1a8a2)
这不是有？

**Comment by RicharPao** [comment]
> ![image](https://user-images.githubusercontent.com/89380218/264000838-c662a0af-c905-4a0c-b0b5-907479f1a8a2.png) 这不是有？

？？？？？？？？你怎么有
![image](https://github.com/liuzhihang/halo-theme-hao/assets/99643174/163ac934-ac65-4a50-96e9-6f13013af563)

**Comment by RicharPao** [comment]
我的没有，我看别人的也没有

**Comment by RicharPao** [comment]
破案了，系统或者浏览器缩放太大的话没有

**Comment by chengzhongxue** [comment]
你屏幕尺寸不够在 2023年8月30日，07:45，RicharPao ***@***.***> 写道：﻿
我的没有，我看别人的也没有
