### ISSUE TITLE
music音乐页面BUG问题

### ISSUE THREAD

**Issue by lzrh123jia** [liuzhihang/halo-theme-hao#458]
### 是什么版本出现了此问题？

1.3.4

### 发生了什么？

![b6ba0239a7fb4aad97aa7e068da4ef5](https://github.com/liuzhihang/halo-theme-hao/assets/90361939/5372ed71-e301-4132-a020-a50eda93ca04)
![0260eccdd7d812dc4d0b0b2997b7e6a](https://github.com/liuzhihang/halo-theme-hao/assets/90361939/02fdeccd-955d-4bb0-8096-94ba539a69a5)
音乐界面加载很慢，经常黑屏。
加载出来后，音乐api无法正常使用，只要使用默认的api，列表就会不按照设置的来，歌单里全是HELLO的歌。
删了api后保存 歌单正常了，但是背景图片不显示。

**Comment by chengzhongxue** [comment]
站点地址
