### ISSUE TITLE
中控台中无法获取Twikoo评论

### ISSUE THREAD

**Issue by RicharPao** [liuzhihang/halo-theme-hao#459]
### 是什么版本出现了此问题？

1.3.3

### 在线站点地址

https://blog.vacuole.top

### 发生了什么？

配置Twikoo评论后在中控台中显示无法获取，应该是只支持插件的评论。
还有个问题就是我看https://liuzhihang.com/的评论支持登录已有帐号和类似Twikoo的自己输入昵称，但是我使用插件评论时就只有登录账号，不能自己输入，https://liuzhihang.com/这个是怎么实现的？

**Comment by chengzhongxue** [comment]
你网站都有问题
缓存问题
