### ISSUE TITLE
感觉文章页面有些丑，同时还有一些其他问题，我都放在这里描述啦~

### ISSUE THREAD

**Issue by Jimecc** [liuzhihang/halo-theme-hao#46]
### 你当前使用的版本

1.0.4

### 描述一下此特性

# 美化文章页面
文章页面的字体感觉可以更小一些，然后将整体布局更加居中，让右侧的菜单导航也更小一些。

# 文章页添加导航信息
导航信息可以在同级目录下加一些灰色的竖线吗，让他更加便于阅读（我是看你的博客的导航，我的博客导航有bug，无法显示，版本1.0.4，稍后反馈）

# 提问一个问题
关于首页最顶端的”这里需要后面适配瞬间的插件“到底是个什么东西呀，我看你的博客好像也没有配，是后面会添加的功能吗？能否做一下简单的描述呢？

**Comment by sun0225SUN** [comment]
https://blog.zhheo.com/
hao整体移植的这款博客，具体效果可以参考下，文章页我觉得还阔以，后期应该可以自己写css修改吧
（刚入坑halo，还没摸明白--）
