### ISSUE TITLE
文章内详细信息（目录）无法显示

### ISSUE THREAD

**Issue by Jimecc** [liuzhihang/halo-theme-hao#47]
### 是什么版本出现了此问题？

1.0.4

### 在线站点地址

http://blog.shary.cc

### 发生了什么？

# 问题描述
可以点击进我的博客看一下，都是目录打不开的状态的，只有”目录“两个字，没有具体的内容。

**Comment by shy-share** [comment]
我看下，正常啊 可以从目录跳转啊
![image](https://user-images.githubusercontent.com/50973219/210956401-6236e802-14a5-4ab6-b991-31c764ed6e11.png)

**Comment by shy-share** [comment]
破案了，黑色主题才会出现这个问题
