### ISSUE TITLE
文章页面增加编辑按钮

### ISSUE THREAD

**Issue by funtime1** [liuzhihang/halo-theme-hao#478]
### 你当前使用的版本

1.3.5

### 描述一下此特性

**需求：**
在账号已登录的情况下,在前台文章页面增加一个编辑按钮,方便直接修改当前文章.
> 现在需要单独打开后台页面，搜索这篇文章，才能进行编辑，比较麻烦。

**Comment by chengzhongxue** [comment]
你截个图看下编辑按钮放在哪个位置比较好，我参考下

**Comment by funtime1** [comment]
一. 编辑按钮个人感觉可以放在以下位置：
1. halo的默认主题是在文章页面的右下角：(这个编辑按钮是全局跟随的，在文章的任意查看位置都可以进行点击)
![image](https://github.com/liuzhihang/halo-theme-hao/assets/90565575/1ea08571-1f14-4157-b799-ba74845b1eee)
2. 日期、评论数那一行都可以（文章开头）
![image](https://github.com/liuzhihang/halo-theme-hao/assets/90565575/a7658122-ad7a-4f77-a1ed-74c22dadeedf)
3. 文章标题后面（文章开头）
![image](https://github.com/liuzhihang/halo-theme-hao/assets/90565575/f2fec316-a1b8-4e70-9cb1-ea962f4d2a5f)

> 编辑按钮放在文章开头的缺点：需要定位到文章开头，才能点击编辑按钮

二. 假如加上了编辑按钮，这就会存在一个登录账号问题，因为编辑文章需要登录账号，那是否还需要添加一个登录控制台的按钮呢。

**Comment by chengzhongxue** [comment]
![image](https://github.com/liuzhihang/halo-theme-hao/assets/89380218/bce8a597-657d-44fb-97c1-0beb10a962b3)
这两个地方加 @funtime1

**Comment by funtime1** [comment]
谢谢大佬! 太赞了。

**Comment by chengzhongxue** [comment]
@funtime1 
![image](https://github.com/liuzhihang/halo-theme-hao/assets/89380218/ea4d61da-59d0-40f9-a180-007d972e9898)
已添加，1.3.7版本更新，这个没有登录是不会出来的
前台登录按钮，正在加
