### ISSUE TITLE
提个建议把css , js资源变成cdn链接

### ISSUE THREAD

**Issue by OPMonday** [liuzhihang/halo-theme-hao#48]
### 你当前使用的版本

1.0.4

### 描述一下此特性

自带cdn链接或给用户提供css,js等文件下载链接让用户使用自己的cdn，这样可以加快halo的访问速度😊。

**Comment by it985** [comment]
可以发布到npm上
【jsd出品，网宿国内节点】
https://npm.elemecdn.com/:package@:version/:file
【知乎出品，网宿国内节点】
https://npm.elemecdn.com/:package@:version/:file
【百度出品，网宿国内节点】
https://code.bdstatic.com/npm/:package@:version/:file
【饿了么出品，网宿国内节点】
https://shadow.elemecdn.com/npm/:package@:version/:file
知乎节点不错

**Comment by it985** [comment]
或者加个选项，加载本地静态文件或者加载npm上的文件

**Comment by liuzhihang** [comment]
<img width="200" alt="image" src="https://user-images.githubusercontent.com/26057042/210574064-a2c43818-7481-4bcd-b0c3-39b76eaf55a6.png">
