### ISSUE TITLE
主题设置的页脚中“底部相关链接”启动了主菜单就没办法取消了

### ISSUE THREAD

**Issue by xiaoheiyo** [liuzhihang/halo-theme-hao#49]
### 是什么版本出现了此问题？

1.0.4

### 发生了什么？

主题设置的页脚中“底部相关链接”启动了主菜单就没办法取消了

### 附加信息

![image](https://user-images.githubusercontent.com/26519690/210135746-5bd29b6e-701a-45a4-addd-5a0f1de294f9.png)

**Comment by liuzhihang** [comment]
添加一个空菜单，然后选择那个空的菜单吧

<img width="1501" alt="image" src="https://user-images.githubusercontent.com/26057042/210137847-d6d82a98-09e0-4da8-a524-e24f3e0699c1.png">

**Comment by xiaoheiyo** [comment]
好家伙，我现在就是这么做的😂
