### ISSUE TITLE
适配友链朋友圈

### ISSUE THREAD

**Issue by Steven-WZH** [liuzhihang/halo-theme-hao#492]
### 你当前使用的版本

1.3.7

### 描述一下此特性

https://fcircle-doc.yyyzyyyz.cn/#/developmentdoc?id=%e5%8f%8b%e9%93%be%e9%a1%b5%e9%80%82%e9%85%8d

**Comment by chengzhongxue** [comment]
不要随便提，看下文档谢谢，这个有
