### ISSUE TITLE
使用halo提供的StackEdit插件markdown编写的链接无法在新窗口打开

### ISSUE THREAD

**Issue by youngledo** [liuzhihang/halo-theme-hao#507]
### 是什么版本出现了此问题？

最新版

### 发生了什么？

使用halo提供的StackEdit插件markdown编写的链接无法在新窗口打开。

我希望的是链接可以在新窗口打开（因为有些链接非本站），而不是在当前窗口。尝试在halo的代码注入中设置，发现并不能完美解决：
![image](https://github.com/liuzhihang/halo-theme-hao/assets/68590897/012ace73-f463-48d2-9bf5-50e8eb45e3e1)

此问题也求助过halo，参考：https://github.com/halo-dev/halo/issues/4640

**Comment by chengzhongxue** [comment]
语法问题，跟主题没关系

**Comment by youngledo** [comment]
> 语法问题，跟主题没关系

能说的更详细点吗，语法指的是上面的js脚本不对吗？

**Comment by chengzhongxue** [comment]
默认的md语法一般都是内链，要自己写外链语法
