### ISSUE TITLE
微信搜一搜模块自定义

### ISSUE THREAD

**Issue by lanbinshijie** [liuzhihang/halo-theme-hao#51]
### 你当前使用的版本

1.0.4

### 描述一下此特性

# 需求
首页微信搜一搜图片是否可以实现自定义？可以将其放在首页的设置中间
如果可以，可以联动一些在线生成这些图片的API完成这项工作。
非常喜欢这样的卡片式主题！作者加油！感谢入坑Halo时遇到了这样好的开源主题。

<img width="1244" alt="image" src="https://user-images.githubusercontent.com/62149873/210508027-7ff5858a-d172-40b4-a5ee-7f0ac8427d50.png">

**Comment by liuzhihang** [comment]
【后台 console -> 外观 -> 主题 -> 侧栏】 可以设置这里的图片，并且也可以通过调整侧栏选择关闭此功能。

<img width="943" alt="image" src="https://user-images.githubusercontent.com/26057042/210511633-4e72eb9e-3daf-418d-8302-e9f31827e53f.png">

**Comment by lanbinshijie** [comment]
感谢，希望可以将这些容易忽略的点放进文档里

**Comment by liuzhihang** [comment]
文档还没有更新，后面会陆续更新文档
