### ISSUE TITLE
代码块复制后 最后面会多出一个空行

### ISSUE THREAD

**Issue by funtime1** [liuzhihang/halo-theme-hao#511]
### 是什么版本出现了此问题？

1.3.9

### 发生了什么？

文章中的代码块复制后, 最后面会自动加上一个多余的空行

**Comment by chengzhongxue** [comment]
文章链接，截图

**Comment by funtime1** [comment]
文章:
https://blog.dwgg.cc:8445/archives/1694946481138
点击代码复制按钮:
![image](https://github.com/liuzhihang/halo-theme-hao/assets/90565575/1d60e22a-ed05-4fb1-b8cd-d509f416f127)
粘贴后:(多了第4行的空白行)
![image](https://github.com/liuzhihang/halo-theme-hao/assets/90565575/6571f673-6250-4120-aa34-0d6f169b0574)

**Comment by chengzhongxue** [comment]
你去看别人的
都是这样


c
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "liuzhihang/halo-theme-hao"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年10月9日(星期一) 晚上10:12
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [liuzhihang/halo-theme-hao] 代码块复制后 最后面会多出一个空行 (Issue #511)





 
文章:
 https://blog.dwgg.cc:8445/archives/1694946481138
 点击代码复制按钮:
 
 粘贴后:(多了第4行的空白行)

**Comment by funtime1** [comment]
大佬, 再看下这个dream主题,没有结尾的空行       https://blog.dwgg.cc:8445/archives/1694946481138
我去简书上找了一篇也没有空行.
https://www.jianshu.com/p/af479b389810

确实是有的有空行,有的没有空行, 这个不算啥问题,可以忽略哈.

**Comment by chengzhongxue** [comment]
是有，但是没多大影响先这样吧

c
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "liuzhihang/halo-theme-hao"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年10月9日(星期一) 晚上10:59
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [liuzhihang/halo-theme-hao] 代码块复制后 最后面会多出一个空行 (Issue #511)





 
大佬, 再看下这个dream主题,没有结尾的空行       https://blog.dwgg.cc:8445/archives/1694946481138
 我去简书上找了一篇也没有空行.
 https://www.jianshu.com/p/af479b389810
 
确实是有的有空行,有的没有空行, 这个不算啥问题,可以忽略哈.
