### ISSUE TITLE
升级2.9.1后 友链页面打不开

### ISSUE THREAD

**Issue by lianlianlianlianlianlian** [liuzhihang/halo-theme-hao#513]
### 是什么版本出现了此问题？

2.9.1

### 发生了什么？

![image](https://github.com/liuzhihang/halo-theme-hao/assets/36120596/5fce0883-5104-4dfd-a967-e146d4284611)

**Comment by lianlianlianlianlianlian** [comment]
测试完毕 不是halo主程序打不开 而是最新主题v1.3.9的问题 我降级到1.3.8就好了

**Comment by lianlianlianlianlianlian** [comment]
不对劲 好像还是2.9.1 halo主程序的锅。。

**Comment by chengzhongxue** [comment]
可以啊

**Comment by chengzhongxue** [comment]
@lianlianlianlianlianlian 解决没

**Comment by lianlianlianlianlianlian** [comment]
太久没玩 原来是链接插件需要更新了 插件更新后就好了 不更新的话就是我说的那种情况
