### ISSUE TITLE
版权声明里作者固定死了 “程序员小航”

### ISSUE THREAD

**Issue by oozry12** [liuzhihang/halo-theme-hao#517]
### 是什么版本出现了此问题？

1.3.9

### 发生了什么？

在`settings.yaml`里相关代码应该写死了。后台主题设置没有地方可以修改
![](https://cdn.ooim.xyz/fc1c116269a5716636cf257b690627c0.png)

```
placeholder: '本文是原创文章，采用 <a target="_blank" href="/cc">CC BY-NC-ND 4.0</a> 协议，完整转载请注明来自 <a href="/" target="_blank" >程序员小航</a>'
```

**Comment by chengzhongxue** [comment]
自己可以设置
文章->版权声明->原创声明内容

**Comment by oozry12** [comment]
默认就是选择原创了的。不管主题后台设置哪个链接，都写死了 `example.com/cc` 跳转，包括作者也是

**Comment by chengzhongxue** [comment]
![image](https://github.com/liuzhihang/halo-theme-hao/assets/89380218/ae71b080-d811-40d4-9bd7-f9c4c294b9be)
这里是可以设置的，你仔细看看

**Comment by oozry12** [comment]
可以考虑把这个设置放在主题后台，不用每一篇文章进行设置

**Comment by sz5032208** [comment]
有没有可能，这里是可以设置的，而且可以设置以后保存的
