### ISSUE TITLE
长文章目录不生效，点不动

### ISSUE THREAD

**Issue by fl1906** [liuzhihang/halo-theme-hao#529]
### 是什么版本出现了此问题？

 1.3.9

### 在线站点地址

https://blog.flya.top/archives/1697716236038#

### 发生了什么？

文章目录无法点击 
![image](https://github.com/liuzhihang/halo-theme-hao/assets/73702449/ad3d4a4c-436f-4e5c-a0e6-0b39e6a5bc82)

**Comment by chengzhongxue** [comment]
已解决
