### ISSUE TITLE
建议增加右键菜单自定义

### ISSUE THREAD

**Issue by lanbinshijie** [liuzhihang/halo-theme-hao#53]
### 你当前使用的版本

1.0.4

### 描述一下此特性

如题，建议增加右键菜单自定义，当前设置下部分连接会到奇怪的地方。
<img width="158" alt="image" src="https://user-images.githubusercontent.com/62149873/210699670-582008a4-5d60-4ebb-9c50-6b5cf1c7a004.png">

**Comment by shy-share** [comment]
@lanbinshijie 这个当初是特意去掉的，是吧 @liuzhihang
