### ISSUE TITLE
iconfont.css 所在源不稳定

### ISSUE THREAD

**Issue by baojunz** [liuzhihang/halo-theme-hao#530]
### 是什么版本出现了此问题？

 https://cdn.cbd.int/hao-theme-static@1.4.1/icon/iconfont.css

### 在线站点地址

https://blog.buuu.cn

### 发生了什么？

页面执行加载后，经常发现 图标无法正常显示，发现是源不稳定导致，建议支持改为本地引用或支持更换源
![585601697890023_ pic](https://github.com/liuzhihang/halo-theme-hao/assets/48702961/baec3eda-eb5e-42ac-b1b8-fdb8f742f240)

**Comment by chengzhongxue** [comment]
已经改成本地 1.4.2
