### ISSUE TITLE
51统计 js报错

### ISSUE THREAD

**Issue by baojunz** [liuzhihang/halo-theme-hao#531]
### 是什么版本出现了此问题？

点击关于我页面 51统计报错

### 发生了什么？

<img width="1709" alt="image" src="https://github.com/liuzhihang/halo-theme-hao/assets/48702961/920a9d23-cf80-43a8-9c93-e09683fc3d92">

**Comment by chengzhongxue** [comment]
你这什么鬼， 这是我的吧

**Comment by lanbinshijie** [comment]
> ### 是什么版本出现了此问题？
> 点击关于我页面 51统计报错
> 
> ### 在线站点地址
> _No response_
> 
> ### 发生了什么？
> <img alt="image" width="1709" src="https://user-images.githubusercontent.com/48702961/277109459-920a9d23-cf80-43a8-9c93-e09683fc3d92.png">
> ### 相关日志输出
> _No response_
> 
> ### 附加信息
> _No response_

注册一下你自己的51la账号，获取自己的链接试试看，可以查看部署文档。
