### ISSUE TITLE
文章分享是否可以增加qq和朋友圈卡片分享

### ISSUE THREAD

**Issue by haoanlan** [liuzhihang/halo-theme-hao#532]
### 你当前使用的版本

1.4.1

### 描述一下此特性

如附加图所示

### 附加信息

![1698145850197](https://github.com/liuzhihang/halo-theme-hao/assets/90305105/c4049808-ac69-45a8-80f3-92eb98866c2e)

**Comment by carolcoral** [comment]
暂无该计划

**Comment by carolcoral** [comment]
在做了，在做了

**Comment by carolcoral** [comment]
1.4.5
