### ISSUE TITLE
新加默认模板页面希望支持大纲显示

### ISSUE THREAD

**Issue by TaCraft-Sociality** [liuzhihang/halo-theme-hao#533]
### 你当前使用的版本

 2.10.0

### 描述一下此特性

新加默认模板页面希望支持大纲显示

**Comment by chengzhongxue** [comment]
什么意思

**Comment by carolcoral** [comment]
目前使用TOC插件可以实现大纲目录：https://github.com/liuzhihang/plugin-tocbot

**Comment by chengzhongxue** [comment]
他说的是页面吧

**Comment by carolcoral** [comment]
> 他说的是页面吧

可以你的页面加好了，只要在“侧边栏”中“自定义页面”也加上“toc”标记也可以实现大纲啊。不过目前自定义页面的侧边栏宽度不对
