### ISSUE TITLE
Internal Server Error: The [theme.yaml] does not conform to the theme specification.

### ISSUE THREAD

**Issue by yShen868** [liuzhihang/halo-theme-hao#54]
### 是什么版本出现了此问题？

Internal Server Error: The [theme.yaml] does not conform to the theme specification.

### 发生了什么？

Internal Server Error: The [theme.yaml] does not conform to the theme specification.

**Comment by shy-share** [comment]
@yShen868 现在最新版本是没有问题，你可以升级一下
> 以后记得把halo版本和 主题版本都写一下
