### ISSUE TITLE
登录之后提交评论按钮会因为用户名称过长超出屏幕范围

### ISSUE THREAD

**Issue by baissroom** [liuzhihang/halo-theme-hao#542]
### 是什么版本出现了此问题？

1.4.2

### 发生了什么？

登录之后提交评论按钮会因为用户名称过长超出屏幕范围

### 附加信息

![image](https://github.com/liuzhihang/halo-theme-hao/assets/130037107/0105d7d5-da12-4bf6-9778-19fe0385c436)

**Comment by chengzhongxue** [comment]
这个得找官方评论插件，不属于主题bug
