### ISSUE TITLE
移动端列表标签重复

### ISSUE THREAD

**Issue by FelicxFoster** [liuzhihang/halo-theme-hao#546]
### 是什么版本出现了此问题？

1.43

### 在线站点地址

https://felicx.eu.org

### 发生了什么？

移动端点击右侧列表，会有重复标签出现，见下图
![Screenshot_2023-11-17-18-05-19-968_com z28j feel-edit](https://github.com/liuzhihang/halo-theme-hao/assets/33318659/976eb8c2-7cb5-49a8-821a-06e7471c2e7b)

**Comment by chengzhongxue** [comment]
这里是左侧菜单和主菜单的

**Comment by chengzhongxue** [comment]
![image](https://github.com/liuzhihang/halo-theme-hao/assets/89380218/10104d66-d668-4c1c-8cfa-9dfe6b5cbe78)
