### ISSUE TITLE
深色模式下评论插件适配有问题

### ISSUE THREAD

**Issue by lanbinshijie** [liuzhihang/halo-theme-hao#55]
### 是什么版本出现了此问题？

1.0.5

### 在线站点地址

http://lib.lanbin.top/

### 发生了什么？

当博客接入评论插件后，发现在深色模式的适配之下出现了一些问题。在深色模式下，评论主题的颜色也是黑色，导致无法看清评论的内容，而浅色模式则没有这样的问题。

![image](https://user-images.githubusercontent.com/62149873/211002032-a9179374-e3d6-4681-adf7-b3e0549203aa.png)
<img width="623" alt="image" src="https://user-images.githubusercontent.com/62149873/211002021-52f66aca-d086-4da8-af4b-90844ebe94d5.png">
<img width="679" alt="image" src="https://user-images.githubusercontent.com/62149873/211002457-0f34116a-e26d-4b98-a930-aacabefdda7f.png">

**Comment by lanbinshijie** [comment]
如果可以，希望Hao主题能够单独配置此项，谢谢！

**Comment by sun0225SUN** [comment]
> 如果可以，希望Hao主题能够单独配置此项，谢谢！

![2023-01-06_19-31-42](https://user-images.githubusercontent.com/79169717/211004398-57ef950f-9006-4ec4-9b4f-bb25bc13db28.png)

**Comment by lanbinshijie** [comment]
> > 如果可以，希望Hao主题能够单独配置此项，谢谢！
> 
> ![2023-01-06_19-31-42](https://user-images.githubusercontent.com/79169717/211004398-57ef950f-9006-4ec4-9b4f-bb25bc13db28.png)

嗯嗯，那我还是先留着吧。另外咱俩交换一下友链吧。

**Comment by lanbinshijie** [comment]
问题还没解决，先不关issue啦

**Comment by sun0225SUN** [comment]
> 问题还没解决，先不关issue啦

哈哈哈，好嘞，已在你站点下留言
