### ISSUE TITLE
文章封面页跨域请求问题

### ISSUE THREAD

**Issue by qanderer** [liuzhihang/halo-theme-hao#550]
### 是什么版本出现了此问题？

 2.10.2

### 在线站点地址

https://www.acgurl.link/

### 发生了什么？

文章封面的随机图片可以正常加载但会在控制台报跨域请求
这个问题出现在文章的详情页里面
在外部比如主页不会出现

### 相关日志输出

```shell
以下是在浏览器f12控制台看到的报错信息
Access to image at 'https://api.acgurl.link/pc.php?raw' from origin 'https://www.acgurl.link' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
Failed to load resource: net::ERR_FAILED
Error: FastAverageColor: Error loading image "https://api.acgurl.link/pc.php?raw".
    at m (index.browser.min.js:2:2843)
    at Image.a (index.browser.min.js:2:5682)
```

### 附加信息

在网上大概搜了搜有关的文章
[https://www.jianshu.com/p/8fa0fb53c183](url)
似乎是js内重复调用这张图片的话浏览器会去缓存里找
这样就会导致与我的站点地址不一即跨域
一个可能的解决方案是在` <img>` 中和 JS 中的 `<img>` 都加上` crossorigin = "anonymous"`

**Comment by chengzhongxue** [comment]
这个你自己试过？

**Comment by qanderer** [comment]
试了
没用
依旧报错，但不影响显示
所以没管他

**Comment by carolcoral** [comment]
该错误是由于浏览器的跨域资源共享 (CORS) 策略引起的。浏览器默认情况下会阻止从一个域（Origin）向另一个域发起的跨域请求。

根据错误信息中的提示，从`https://www.acgurl.link`域名的网页上发起了一个跨域请求到`https://api.acgurl.link/pc.php?raw`资源，但是服务器未返回正确的CORS头部信息（Access-Control-Allow-Origin）。

要解决这个错误，你需要在服务器端进行配置，以允许来自`https://www.acgurl.link`域的跨域请求。具体的配置方法取决于你使用的服务器软件和语言。

如果你使用的是 Apache 服务器，可以通过添加以下代码到服务器配置文件或者.htaccess文件中来解决：

```
Header set Access-Control-Allow-Origin "https://www.acgurl.link"
```

如果你使用的是 Nginx 服务器，可以在服务器配置文件的`location`块中添加以下代码：

```
add_header Access-Control-Allow-Origin https://www.acgurl.link;
```

如果你使用的是其他服务器软件或语言，你可以搜索相关的配置方法，或者咨询服务器管理员或开发者。

注意，这种配置将允许`https://www.acgurl.link`域的网页发起跨域请求到`https://api.acgurl.link/pc.php?raw`资源。确保你只允许来自可信的域的跨域请求，以保证安全性。

如果你没有服务器的控制权限，或者无法进行服务器端的配置，你可以尝试将资源下载到服务器本地，然后通过服务器端提供的接口来获取资源。这样可以避免浏览器的CORS限制。

希望这些信息对你有帮助，如果你需要进一步的帮助，请提供更多的代码和相关的服务器信息。
