### ISSUE TITLE
页尾最后一行会被广告拦截器屏蔽

### ISSUE THREAD

**Issue by acgurl** [liuzhihang/halo-theme-hao#551]
### 是什么版本出现了此问题？

 2.10.2

### 在线站点地址

https://www.acgurl.link/

### 发生了什么？

页尾的最后一行即有备案号的那一行会被广告拦截器屏蔽
我使用的的广告拦截器为`AdBlocker Ultimate`
且被拦截后没有任何提示
可以考虑在被拦截后显示一段提示吗
这个备案号被拦截的话还是不太好的

### 附加信息

https://github.com/liuzhihang/halo-theme-hao/assets/139052986/f9429a30-3d33-4aa9-929f-badd00d8f5e1

**Comment by carolcoral** [comment]
好的，计划修复

**Comment by carolcoral** [comment]
1.4.4版本中增加了检测footer被拦截出现alert提醒

**Comment by 2019YKL** [comment]
您好，alert提醒可否修改为登录用户可见？或者提供关闭选项，因为有些主题用户并用不上。

更新版本后，不论什么时候都会显示这个提醒，无论你是否选择显示备案相关选项，这对于游客是否算是一种负优化？

我看到issue提出者的网站，目前也会提示这个提醒。

然后，我用的是adguard，目前“AdBlocker Ultimate”的提示词并不太妥当，容易误导博主和用户。

希望您参考一下我的建议~

**Comment by carolcoral** [comment]
> 您好，alert提醒可否修改为登录用户可见？或者提供关闭选项，因为有些主题用户并用不上。
> 
> 更新版本后，不论什么时候都会显示这个提醒，无论你是否选择显示备案相关选项，这对于游客是否算是一种负优化？
> 
> 我看到issue提出者的网站，目前也会提示这个提醒。
> 
> 然后，我用的是adguard，同样会显示弹窗，目前“AdBlocker Ultimate”的提示词是否不太妥当，容易误导博主和用户？
> 
> 希望您参考一下我的建议~

好的，下个版本考虑优化下

**Comment by carolcoral** [comment]
这个是广告屏蔽插件的问题，建议关闭你本地的广告屏蔽插件或者更换为别的广告屏蔽插件，例如 [adblockplus](https://accounts.adblockplus.org/zh_CN/)

**Comment by carolcoral** [comment]
是的，这个和主题、博客系统没有关系。这个提醒是因为你本地浏览器使用的广告拦截插件导致的问题，可以根据前面的回复更换广告拦截插件。

**Comment by carolcoral** [comment]
你可以尝试停用当前广告拦截插件后刷新重试

**Comment by 2019YKL** [comment]
> 是的，这个和主题、博客系统没有关系。这个提醒是因为你本地浏览器使用的广告拦截插件导致的问题，可以根据前面的回复更换广告拦截插件。

好的，感谢您的解答，我尝试过关掉广告插件，确实可以解决问题。

![image](https://github.com/liuzhihang/halo-theme-hao/assets/51532948/a3cc6503-70ef-4c4c-a6b1-b64491d19b85)

我发现这里设置关掉页脚显示也可以不再被提醒（因为我个人不太需要这个页脚）。

再次感谢您的解答，祝您生活愉快~

**Comment by carolcoral** [comment]
> > 是的，这个和主题、博客系统没有关系。这个提醒是因为你本地浏览器使用的广告拦截插件导致的问题，可以根据前面的回复更换广告拦截插件。
> 
> 好的，感谢您的解答，我尝试过关掉广告插件，确实可以解决问题。
> 
> ![image](https://private-user-images.githubusercontent.com/51532948/293816331-a3cc6503-70ef-4c4c-a6b1-b64491d19b85.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQyNDYzNDksIm5iZiI6MTcwNDI0NjA0OSwicGF0aCI6Ii81MTUzMjk0OC8yOTM4MTYzMzEtYTNjYzY1MDMtNzBlZi00YzRjLWE2YjEtYjY0NDkxZDE5Yjg1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTAzVDAxNDA0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE4YzM5YmM2YmYxNzY2MzRiMTBhMzY0ZTQ0ODZkOGFkMzAzYjg2NDhiMDUzNGZlNTBiZGI1M2JkMGVjYzIxNmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.anz5dlAx70mXwh7GggPmlqy9fgFRsoiydek2NWNZs2Q)
> 
> 我发现这里设置关掉页脚显示也可以不再被提醒（因为我个人不太需要这个页脚）。
> 
> 再次感谢您的解答，祝您生活愉快~

是的，隐藏底部也不会提醒，提醒只会在开启了底部页脚并且被广告拦截器拦截后才会提醒

**Comment by Omoinemie** [comment]
但是免像用户的，不能要求所有用户都把去广告关闭吧，这是不现实的，只能优化程序，不让去广告插件拦截。
如果是我访问某个网站，让我关闭去广告，那我就直接把这网站拉黑了，宁愿不用你。

**Comment by carolcoral** [comment]
> 但是面向用户的，不能要求所有用户都把去广告关闭吧，这是不现实的，只能优化程序，不让去广告插件拦截。 如果是我访问某个网站，让我关闭去广告，那我就直接把这网站拉黑了，宁愿不用它。

那你需要去联系广告拦截插件的开发者进行修复处理

**Comment by flycati** [comment]
> 但是面向用户的，不能要求所有用户都把去广告关闭吧，这是不现实的，只能优化程序，不让去广告插件拦截。 如果是我访问某个网站，让我关闭去广告，那我就直接把这网站拉黑了，宁愿不用它。

这篇博客或许可以满足你的需求：[Halo博客Hao主题如何移除广告拦截提醒](https://blog.flycat.tech/archives/halo-blog-hao-theme-how-to-remove-ad-blocking-alerts)

**Comment by acgurl** [comment]
没想得这个issue的讨论挺多的
我对此有一个新的建议
原先的alert弹窗确实有点太明显了，有点影响用户体验
不妨将提醒方式更改为在页面上方显示一条会自己关闭的提示，就像按F12和复制时的那个黄色的提醒一样
如果有开发者有更好的想法也可以修改为更合适的样式
祝您生活愉快！
