### ISSUE TITLE
(waline)最近评论未自动定位到该评论的位置上

### ISSUE THREAD

**Issue by zhajianjun** [liuzhihang/halo-theme-hao#552]
### 是什么版本出现了此问题？

1.4.3

### 在线站点地址

https://www.ticho.top/

### 发生了什么？

评论系统设置为“waline”后，主页“最近评论”点击进入相关页面后，没有自动定位到该评论的位置上

**Comment by carolcoral** [comment]
详细描述下过程呢

**Comment by carolcoral** [comment]
1.4.4版本应该修复了，如果再次出现可以重新提交issues。本次issues就关闭了哈

**Comment by zhajianjun** [comment]
没有哦！问题是，主页的最近评论模块点击任一评论，应该自动跳转到相应页面，并自动定位到该评论的位置，但是并定位到该位置，仅仅是跳转页面而已，仅waline评论会有这个问题。

**Comment by zhajianjun** [comment]
> 1.4.4版本应该修复了，如果再次出现可以重新提交issues。本次issues就关闭了哈

没有哦！问题是，主页的最近评论模块点击任一评论，应该自动跳转到相应页面，并自动定位到该评论的位置，但是并定位到该位置，仅仅是跳转页面而已，仅waline评论会有这个问题。

**Comment by carolcoral** [comment]
新包才上传，试试1.4.4的新包呢，另外npm资源还没同步，使用“本地”资源哈

**Comment by zhajianjun** [comment]
> 新包才上传，试试1.4.4的新包呢，另外npm资源还没同步，使用“本地”资源哈

好，谢啦！我更新下缓存再观察观察。
