### ISSUE TITLE
halo主题，有个bug，在顶部选项中，Banner 左侧这一栏，选择了个人技术栈，也上传了背景图，但首页那一块就是一片白，不显示图。

### ISSUE THREAD

**Issue by sameceo** [liuzhihang/halo-theme-hao#553]
### 是什么版本出现了此问题？

1.4.3

### 发生了什么？

halo主题，有个bug，在顶部选项中，Banner 左侧这一栏，选择了个人技术栈，也上传了背景图，但首页那一块就是一片白，不显示图。

**Comment by expliyh** [comment]
我这边是会显示图片，但是周围的边框没有了

**Comment by chengzhongxue** [comment]
框是设置的颜色啊，你是不是默认颜色没改

**Comment by zhuyouhe0301** [comment]
你好，我测试了一下你所说的情况，其原因可能有以下几种：
1. 个人技术栈添加的icon个数太少，推荐 ≥ 8个
2. icon的图片索引链接无效，可以先上传上传本地测试一下
3. 每个icon的背景颜色设置有问题

**Comment by carolcoral** [comment]
可以出来，但是需要你设置多个图标（至少4个以上）

<img width="684" alt="image" src="https://github.com/liuzhihang/halo-theme-hao/assets/8952687/203af6a7-66ad-469c-926a-50b8d639a89a">
