### ISSUE TITLE
页脚  一直显示菜单栏名称   怎么隐藏掉呀

### ISSUE THREAD

**Issue by rational-stars** [liuzhihang/halo-theme-hao#558]
<img width="1485" alt="image" src="https://github.com/liuzhihang/halo-theme-hao/assets/65513250/7859dbf6-06e5-4af2-998a-6d42a700b438">

**Comment by rational-stars** [comment]
人都是逼出来的  
(你的域名地址/apis/api.console.halo.run/v1alpha1/themes/theme-hao/config) 找到这个接口之后在请求体配置项中的 footer 里面的 menu的值删除掉 也就是改成空字符串  发送请求就 ok 了

**Comment by Wing-Li** [comment]
选择一个空菜单
<img width="1067" alt="image" src="https://github.com/liuzhihang/halo-theme-hao/assets/12133489/dccfd9c3-948d-44cd-b5ba-2e49f81e3c32">
<img width="524" alt="image" src="https://github.com/liuzhihang/halo-theme-hao/assets/12133489/1df7362f-b229-40e4-b947-5194df7f459f">
