### ISSUE TITLE
侧边栏配置的“分类”和“标签”模块有问题

### ISSUE THREAD

**Issue by lanbinshijie** [liuzhihang/halo-theme-hao#56]
### 是什么版本出现了此问题？

1.0.5

### 在线站点地址

http://lib.lanbin.top/

### 发生了什么？

<img width="422" alt="image" src="https://user-images.githubusercontent.com/62149873/211003676-b7f68af5-22af-4a5b-885e-3cc973aa1a27.png">

这几项最初的提示是“如果设置的数值小于0则展示全部”且默认值为-1，
但是后面发现小于等于0的值会导致直接不显示任何东西：
<img width="237" alt="image" src="https://user-images.githubusercontent.com/62149873/211003535-6f147dd5-8d49-409e-bc59-325e65bec72d.png">
如上图所示，正确的效果如下图所示
<img width="214" alt="image" src="https://user-images.githubusercontent.com/62149873/211003382-2485c6e3-37d5-4b81-854e-0b5ca7f689e4.png">

**Comment by AirboZH** [comment]
https://github.com/liuzhihang/halo-theme-hao/blob/c69fc3abf54f6625ab1467b48cf2c5098dad0623/templates/modules/widgets/aside/categories.html#L11
https://github.com/liuzhihang/halo-theme-hao/blob/c69fc3abf54f6625ab1467b48cf2c5098dad0623/templates/modules/widgets/aside/tags.html#L12

没有判断为负的情况,

尝试有效：
`th:if="${categoryQuantity >= 0 && iterStat.index < categoryQuantity  ||  categoryQuantity < 0}">`

**Comment by liuzhihang** [comment]
@JohnNiang @shy-share sh 来个PR 吧

**Comment by ruibaby** [comment]
https://github.com/liuzhihang/halo-theme-hao/blob/c69fc3abf54f6625ab1467b48cf2c5098dad0623/templates/modules/widgets/aside/categories.html#L5

用这个方法即可：https://docs.halo.run/developer-guide/theme/finder-apis/category#listpagesize

```
${categoryFinder.list(1, categoryQuantity)}
```

不需要这么复杂。
