### ISSUE TITLE
代码块渲染出错

### ISSUE THREAD

**Issue by L1102** [liuzhihang/halo-theme-hao#560]
### 是什么版本出现了此问题？

1.4.3

### 发生了什么？

进入含有代码的文章后没有正确的渲染出代码块的主题，需要再次刷新网页才行，我浏览的时候百分百会触发。

### 附加信息

错误显示：
![QQ截图20231208201619](https://github.com/liuzhihang/halo-theme-hao/assets/75559619/13fb714a-db06-4769-a6f2-d44ea582d07e)

正确的：
![QQ截图20231208201637](https://github.com/liuzhihang/halo-theme-hao/assets/75559619/5baa6c90-ba76-4659-b1bb-f8945599fa6e)

**Comment by chengzhongxue** [comment]
地址给一个

**Comment by L1102** [comment]
https://lannnn.cn




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年12月10日(星期天) 晚上8:37
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [liuzhihang/halo-theme-hao] 代码块渲染出错 (Issue #560)





 
地址给一个

**Comment by chengzhongxue** [comment]
删掉toc的插件

**Comment by carolcoral** [comment]
@L1102 删除代码块插件，使用主题的“代码块”
