### ISSUE TITLE
51la样式出现问题

### ISSUE THREAD

**Issue by xialiu666i** [liuzhihang/halo-theme-hao#561]
### 是什么版本出现了此问题？

 1.4.3

### 在线站点地址

blog.xialiu.online

### 发生了什么？

51la卡片样式一直是如图所示 已配置统计ID
<img width="1027" alt="iShot_2023-12-10_17 47 46" src="https://github.com/liuzhihang/halo-theme-hao/assets/88200654/9a33cccb-6718-48f9-8c32-5c512f765902">

**Comment by chengzhongxue** [comment]
51la的挂件开没有

**Comment by carolcoral** [comment]
@xialiu666i 查看文档，检查是否正确完成配置https://www.yuque.com/liuzhihangs/halo-theme-hao/eeoayhggq5a7wh3u#S2YQC
