### ISSUE TITLE
归档怎么在右侧显示序号

### ISSUE THREAD

**Issue by loveyexian** [liuzhihang/halo-theme-hao#562]
### 是什么版本出现了此问题？

最新版

### 在线站点地址

http://bbs.xiaofuma.top/archives

### 发生了什么？

![Snipaste_2023-12-14_08-59-05](https://github.com/liuzhihang/halo-theme-hao/assets/17665882/3a837baf-c6b2-465d-b30c-245d0d07d527)
怎么在右侧显示这个序号呢？

**Comment by chengzhongxue** [comment]
没有
