### ISSUE TITLE
可以添加一个“网站收藏”页面吗？

### ISSUE THREAD

**Issue by Wing-Li** [liuzhihang/halo-theme-hao#564]
### 你当前使用的版本

1.4.2

### 描述一下此特性

https://www.lylyl.cn/my-sites 

类似这样。

其实就是类似友链的页面，只是没有友链顶部的 随机访问 和 申请友链。

**Comment by carolcoral** [comment]
用这个实现的，不需要单独的收藏页面：https://kunkunyu.com/archives/1693149289488
https://blog.cnkj.site/services
