### ISSUE TITLE
建议文章增加最后一次更新时间显示

### ISSUE THREAD

**Issue by UPToZ-Core** [liuzhihang/halo-theme-hao#582]
### 你当前使用的版本

1.4.3

### 描述一下此特性

看到别人的博客，文章的创建时间和最后一次更新时间很醒目，甚至会有提示阅读的人，文章距离最后一次更新过去了多少天，提示读者该文章可能存在过时内容。

**Comment by carolcoral** [comment]
下次，下次更新

**Comment by carolcoral** [comment]
1.4.5版本更新
