### ISSUE TITLE
文章封面显示创建时间和更新时间中存在的一些问题

### ISSUE THREAD

**Issue by UPToZ-Core** [liuzhihang/halo-theme-hao#589]
### 是什么版本出现了此问题？

1.4.5

### 在线站点地址

https://blog.uptoz.cn/

### 发生了什么？

1.创建时间和更新时间存在一些位置和显示的冲突。
2.文章标题超过一行以上，创建时间和更新时间会和标题重叠。
3.感觉字体有点偏大，应该稍微小一点，与下边的文章标签的大小差不多比较合适。
4.与主题原有文章创建时间重复显示了。

### 附加信息

![image](https://github.com/liuzhihang/halo-theme-hao/assets/73866989/a6448a0d-5d44-47c7-bce9-26c4501e785c)
![image](https://github.com/liuzhihang/halo-theme-hao/assets/73866989/443d1a8b-1793-4dd7-a43a-d9ec236219e1)

**Comment by carolcoral** [comment]
了解了，计划修复

**Comment by UPToZ-Core** [comment]
除了PC端的样式，移动端的样式也要修一下

**Comment by carolcoral** [comment]
已优化，等下个版本发
