### ISSUE TITLE
Bug 清单

### ISSUE THREAD

**Issue by sun0225SUN** [liuzhihang/halo-theme-hao#59]
### 是什么版本出现了此问题？

v1.0.5

### 在线站点地址

https://blog.sunguoqi.com/

### Bug清单

<details>
<summary>✅主题图标</summary>

- [x] 主题未引入`font-awesome`图标，导致网站上的一些图标无法正常加载
    `<link rel="stylesheet" href="https://cdn.staticfile.org/font-awesome/6.2.0/css/all.min.css">`<br/>

    ![image](https://user-images.githubusercontent.com/79169717/211192245-06aa1b82-161e-4d85-b1be-5ed86b7fa673.png)

</details>

<details>
<summary>菜单项</summary>

- [x] #104
	         ![Pasted image 20230108171335](https://user-images.githubusercontent.com/79169717/211190646-9d78f491-f809-4ed9-ae29-4e54c26c3e83.png)
                 ![Pasted image 20230108171300](https://user-images.githubusercontent.com/79169717/211190683-031c905a-fd1c-4c2d-9629-4a33ba2e5636.png)
                 ![Pasted image 20230108172152](https://user-images.githubusercontent.com/79169717/211190719-7cb46ba7-8558-4f65-9623-bb406c83d3a6.png)
</details>

<details>
<summary>右键菜单</summary>

- [x] #106

- `分类`、`标签`、`隐私协议` `版权协议`等页面URL地址和实际地址不匹配<br/>
- ![Pasted image 20230108172508](https://user-images.githubusercontent.com/79169717/211190792-7f704d2b-eb6d-4f3a-9b86-40a46f9cfa90.png)
		        分类页面地址：`https://blog.sunguoqi.com/categories`
		        标签页面地址：`https://blog.sunguoqi.com/tags`
		        ...
</details>

<details>
<summary>功能按钮</summary>

- [x] #105
    ![Pasted image 20230108173045](https://user-images.githubusercontent.com/79169717/211190765-a82a157c-83ca-4fc3-a027-c813f4c5fa6f.png)
</details>

<details>
<summary>插件适配</summary>

- [x] 评论插件
    - 评论插件暂时无法自定义CSS样式，导致暗色模式下，无法看清评论内容<br/>
                 ![Pasted image 20230108174801](https://user-images.githubusercontent.com/79169717/211190891-bddb8a6e-6bc1-4da7-bac8-798332159463.png)
- [ ] #109
    - 使用`ByteMD`插件编写的文章，目录插件只能生成目录，无法获取锚点<br/>
                 ![Pasted image 20230108175001](https://user-images.githubusercontent.com/79169717/211190988-52acfa9c-09f3-44be-866e-3aec554f5423.png)

- [x] 代码高亮插件
    - 暗色模式下，代码高亮会覆盖一层阴影<br/>
                 ![Pasted image 20230108175236](https://user-images.githubusercontent.com/79169717/211190893-9e189a13-4540-43f1-8b95-4c1953398880.png)

- [x] #107
    - 暗色模式下，搜索插件的样式需要适配（搜索框也应该变成暗色）<br>
                 ![Pasted image 20230108175757](https://user-images.githubusercontent.com/79169717/211190896-054c4dcd-c109-452c-a152-7dadb4ddc325.png)

- [ ] #110
    - 想在友链页面加入自定义文案内容（非bug，但感觉这个应该是刚需，所以还是放进来了）<br>
![Pasted image 20230108181108](https://user-images.githubusercontent.com/79169717/211190905-299e2fb5-5a2e-4812-a67d-e69555cb7977.png)
![Pasted image 20230108180044](https://user-images.githubusercontent.com/79169717/211190901-0de657ad-7855-4458-b23e-96b56cb924b0.png)
</details>

# BUG补充
@lanbinshijie :
- [x] #108

    如图所示，在暗黑模式下，分割线的样式会看不清。
<img width="554" alt="image" src="https://user-images.githubusercontent.com/62149873/211238238-f2531a67-9fbd-4799-8763-ce1e9b5fb76c.png">
<img width="610" alt="image" src="https://user-images.githubusercontent.com/62149873/211238279-a694ec99-546d-4633-b0ef-57a692f765f7.png">

### 附加信息

无

**Comment by lanbinshijie** [comment]
666（doge）

**Comment by it985** [comment]
666（doge）

**Comment by lanbinshijie** [comment]
# BUG补充
<details> 
    <summary>暗黑模式下分割线问题</summary>

    如图所示，在暗黑模式下，分割线的样式会看不清。
<img width="554" alt="image" src="https://user-images.githubusercontent.com/62149873/211238238-f2531a67-9fbd-4799-8763-ce1e9b5fb76c.png">
<img width="610" alt="image" src="https://user-images.githubusercontent.com/62149873/211238279-a694ec99-546d-4633-b0ef-57a692f765f7.png">


</details>

**Comment by sun0225SUN** [comment]
> # BUG补充
> 暗黑模式下分割线问题
> ```
> 如图所示，在暗黑模式下，分割线的样式会看不清。
> ```
> 
> <img alt="image" width="554" src="https://user-images.githubusercontent.com/62149873/211238238-f2531a67-9fbd-4799-8763-ce1e9b5fb76c.png"> <img alt="image" width="610" src="https://user-images.githubusercontent.com/62149873/211238279-a694ec99-546d-4633-b0ef-57a692f765f7.png">

666（doge）

**Comment by liuzhihang** [comment]
让我休息休息

**Comment by shy-share** [comment]
@liuzhihang 建议还是不要这样放在一起吧，本身提供的bug标签已经可以区分哪些是bug了，这都写在一起 都不知道哪个解决了没有

**Comment by AirboZH** [comment]
麻烦孙哥把无需列表换成checkbox`- [ ]`
- [ ] 1
- [x] 2

我会尝试解决这些问题
