### ISSUE TITLE
显示了复制成功，但其实没复制出来

### ISSUE THREAD

**Issue by shenchongi** [liuzhihang/halo-theme-hao#591]
### 是什么版本出现了此问题？

 1.4.5

### 在线站点地址

http://www.shenchong.ltd:60001/

### 发生了什么？

用了这个主题后全站的文字都无法复制出来，但是网站是显示复制成功了
可以确定是主题问题，因为我换了其他主题是可以正常复制了
我也想自己解决这个问题，奈何实力不够，看半天没看出来

**Comment by carolcoral** [comment]
请使用 `https` 访问即可
