### ISSUE TITLE
关于页面居住地栏裁切有问题

### ISSUE THREAD

**Issue by haoanlan** [liuzhihang/halo-theme-hao#597]
### 是什么版本出现了此问题？

1.4.6

### 在线站点地址

https://blog.404notfound.space/about

### 发生了什么？

![image](https://github.com/liuzhihang/halo-theme-hao/assets/90305105/4a0b325c-731c-4de7-a7c4-7d2e39bafb54)

**Comment by carolcoral** [comment]
下个版本已修复

**Comment by carolcoral** [comment]
可以下载beta版本试试 https://github.com/liuzhihang/halo-theme-hao/releases/tag/v1.4.7-beta1
