### ISSUE TITLE
Todo 清单

### ISSUE THREAD

**Issue by sun0225SUN** [liuzhihang/halo-theme-hao#60]
### 你当前使用的版本

v1.0.5

### 描述一下此特性

- 增加归档页面
  - 功能参考如下<br>
![Pasted image 20230108174219](https://user-images.githubusercontent.com/79169717/211191668-2e7643d2-8a5f-4728-82fc-6cae3714e5e6.png)

- 文章顶部导航栏显示文章标题
  - 功能参考如下<br>
![Pasted image 20230108180418](https://user-images.githubusercontent.com/79169717/211191678-e8330d82-9eb2-4516-b938-c93cbc25145d.png)

- 文章发表时间
  - 功能参考如下<br>
![Pasted image 20230108180331](https://user-images.githubusercontent.com/79169717/211191683-2ef2885b-344f-4664-af42-2bd517fedf6d.png)

- 站点信息处希望增加 `建站天数`，`全站字数`
  - 功能参考如下<br>
![Pasted image 20230108180539](https://user-images.githubusercontent.com/79169717/211191690-00a2f376-5f42-4b8f-a922-6b51e133b519.png)
- 开发音乐播放器插件
  - 功能参考如下<br>
![Pasted image 20230108180745](https://user-images.githubusercontent.com/79169717/211191697-422d3624-6de8-4f99-a6dd-bfda70715638.png)

### 附加信息

无

**Comment by it985** [comment]
+1

**Comment by liuzhihang** [comment]
先不要着急，年底了，让我休息休息

**Comment by shy-share** [comment]
- 归档页面   未完成
- 文章顶部导航栏显示文章标题 已完成
- 文章发表时间  已完成
- 站点信息处希望增加 建站天数，全站字数  还差全站字数，建站天数已完成
- 开发音乐播放器插件 未完成

**Comment by shy-share** [comment]
@sun0225SUN 以后还是把功能分开写，不要这样写了，混合在一起没办法看进度的

**Comment by sun0225SUN** [comment]
> @sun0225SUN 以后还是把功能分开写，不要这样写了，混合在一起没办法看进度的

收到，当时本来想让航哥速战速决的，所以写一块了（狗头）

**Comment by AirboZH** [comment]
@sun0225SUN 
全站字数Halo 似乎没有提供，应该很难做了
其余的除音乐播放器插件都完成了。
checkbox`- [x]`表示完成。麻烦更新一下
