### ISSUE TITLE
使用Artalk评论，出现了报错

### ISSUE THREAD

**Issue by UPToZ-Core** [liuzhihang/halo-theme-hao#602]
### 是什么版本出现了此问题？

1.4.6

### 在线站点地址

https://blog.uptoz.cn/

### 发生了什么？

使用Artalk评论，出现了报错！

### 附加信息

![image](https://github.com/liuzhihang/halo-theme-hao/assets/73866989/5aac17d1-70f6-48fe-ba8d-8ecb5099ec66)

**Comment by UPToZ-Core** [comment]
![ff4b81a938f5d9cc2fda620e1cf11f7](https://github.com/liuzhihang/halo-theme-hao/assets/73866989/ddde8bd0-a273-4183-bbca-579bc30c7bc3)

**Comment by HenryZeng-Zero** [comment]
检测结果：
+ 前端js和css和后端版本不一致导致

解决:
![图片](https://github.com/liuzhihang/halo-theme-hao/assets/36284614/584629e7-c663-44bd-b945-b2b93096c70d)

+ 使用artalk提供的资源
     >你的管理地址+/dist/Artalk.js
     >你的管理地址+/dist/Artalk.css

+ 也可以使用官方CDN的资源，但是要手动指定版本

**Comment by UPToZ-Core** [comment]
> 检测结果：
> 
> * 前端js和css和后端版本不一致导致
> 
> 解决: ![图片](https://private-user-images.githubusercontent.com/36284614/294835886-584629e7-c663-44bd-b945-b2b93096c70d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ3MDIzODksIm5iZiI6MTcwNDcwMjA4OSwicGF0aCI6Ii8zNjI4NDYxNC8yOTQ4MzU4ODYtNTg0NjI5ZTctYzY2My00NGJkLWI5NDUtYjJiOTMwOTZjNzBkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA4VDA4MjEyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFjNTYyNzNmODNkNzgwNzc2MjNmOGNlYWE5MjY3MTA2ZDZjMzgyMDcxYWQyY2VhOTdiNzM4MjczYWE5ZTQ3M2YmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.VqGS4FWZnXWNpofCPHfXjWI5thsaqajXwkyC4nxflBI)
> 
> * 使用ARTALK提供的资源
>   > 你的管理地址+/dist/Artalk.js
>   > 你的管理地址+/dist/Artalk.css
> * 也可以使用官方CDN的资源，但是要手动指定版本

无效，问题依然存在。

**Comment by HenryZeng-Zero** [comment]
已经修复
