### ISSUE TITLE
备案信息填了，也在页脚启用了，但是网站内没有！

### ISSUE THREAD

**Issue by benjonc** [liuzhihang/halo-theme-hao#606]
### 是什么版本出现了此问题？

 1.4.6

### 在线站点地址

cynthia.life

### 发生了什么？

备案信息填了，也在页脚启用了，但是网站内没有！

**Comment by xyhcode** [comment]
<img width="968" alt="image" src="https://github.com/liuzhihang/halo-theme-hao/assets/64968400/03fdc80f-8513-4975-9273-c823d9fa3447">

**Comment by carolcoral** [comment]
<img width="1481" alt="image" src="https://github.com/liuzhihang/halo-theme-hao/assets/8952687/e5d24108-c4de-4b99-876c-5cbd3d625b02">

这个不就是备案信息么

**Comment by carolcoral** [comment]
<details><summary>Details</summary>
<p>

长时间未回复，执行关闭

</p>
</details>
