### ISSUE TITLE
建议增加资源加载提示

### ISSUE THREAD

**Issue by lanbinshijie** [liuzhihang/halo-theme-hao#61]
### 你当前使用的版本

1.0.5

### 描述一下此特性

希望能够增加如图功能，在资源没有加载完成之前，有一个这样的加载页面。哪怕时间很短，会让用户体验感稍稍增加。

<img width="969" alt="image" src="https://user-images.githubusercontent.com/62149873/211561680-4ebebc16-3475-428a-b9bb-7662590802e4.png">

一点小建议，望采纳❤️
（为什么不在TODO列表加呢？因为我想水一个Issue [笑] ）😂

**Comment by liuzhihang** [comment]
好的 好的，这个之前其实是有的，被关掉了。

**Comment by shy-share** [comment]
@lanbinshijie 其实你可以尝试自己来处理这个问题，顺便水个 pr
