### ISSUE TITLE
关闭 “文章主色匹配图片颜色” 导致文章部分区域主题色丢失

### ISSUE THREAD

**Issue by HenryZeng-Zero** [liuzhihang/halo-theme-hao#610]
### 是什么版本出现了此问题？

1.4.6

### 在线站点地址

https://developer-zeng.com/

### 发生了什么？

“文章主色匹配图片颜色” 打开状态：
![图片](https://github.com/liuzhihang/halo-theme-hao/assets/36284614/d39ccfdb-f9e6-4da6-96cb-5d40b46f6792)

“文章主色匹配图片颜色” 处于关闭状态，背景颜色丢失
+ 白天状态：
    + 主页
    ![图片](https://github.com/liuzhihang/halo-theme-hao/assets/36284614/196c7337-c7aa-4f6b-950c-17a72c21723a)

    + 正文
    ![图片](https://github.com/liuzhihang/halo-theme-hao/assets/36284614/e0315ea8-7581-47a3-adb3-b18d07286a80)

+ 黑暗状态下：
     + 主页
     ![图片](https://github.com/liuzhihang/halo-theme-hao/assets/36284614/3e599292-3c42-468f-9599-142f87f6312a)
     左上角`site-name`区域主题色正常，但是`profile`区依然异常

     + 正文
     ![图片](https://github.com/liuzhihang/halo-theme-hao/assets/36284614/74b71cea-705b-4105-bf7f-b934e76e4afa)
     颜色发生了丢失（虽然相对而言是变得好看了）

### 附加信息

期望效果： 在关闭 “文章主色匹配图片颜色” 后

+ 首页和的`profile`区域和`site-name`区域的背景色是 主题设置>样式 中定义的颜色

**Comment by carolcoral** [comment]
https://github.com/liuzhihang/halo-theme-hao/pull/613 已合并

**Comment by HenryZeng-Zero** [comment]
经过测试：并非主题问题
