### ISSUE TITLE
侧边栏内容设置项中，去除 文章页 和 首页 配置中的profile项会导致界面显示异常

### ISSUE THREAD

**Issue by HenryZeng-Zero** [liuzhihang/halo-theme-hao#611]
### 是什么版本出现了此问题？

1.4.6

### 在线站点地址

https://developer-zeng.com/

### 发生了什么？

加入profile项：

![图片](https://github.com/liuzhihang/halo-theme-hao/assets/36284614/a8016e12-8f85-4766-9e7f-ddeb2c01b8a0)

|首页|文章页|
|-|-|
|![图片](https://github.com/liuzhihang/halo-theme-hao/assets/36284614/b9cd8817-c967-4fc6-9902-28417c54b3b7)|![图片](https://github.com/liuzhihang/halo-theme-hao/assets/36284614/8c997c67-9b9f-4f27-9e00-741c5e16db84)|

去除profile项：
![图片](https://github.com/liuzhihang/halo-theme-hao/assets/36284614/6ec49b9a-ef6e-41fd-9067-238567b2e558)

|首页|文章页|
|-|-|
|![图片](https://github.com/liuzhihang/halo-theme-hao/assets/36284614/d6d5ad1c-5ac1-4d5f-82bd-dfbaa843240b)|![图片](https://github.com/liuzhihang/halo-theme-hao/assets/36284614/cb26d76c-070e-42e6-adbc-bcfa282e9b38)|

bug列表：
+ 首页 侧边栏第一个卡片拥有了profile的底色属性。
+ 文章页 侧边栏卡片间距为0，挤在一起。

### 附加信息

提供部分解决方法：
+ 【文章页 侧边栏卡片间距为0，挤在一起。】的解决办法：
![图片](https://github.com/liuzhihang/halo-theme-hao/assets/36284614/d551bfff-f715-4acd-ac7e-405b613fe895)

**Comment by carolcoral** [comment]
去掉`profile`后侧边栏确实会存在该问题，可以直接在`系统` - `设置` - `代码注入` - `页脚`中直接添加以下代码: 

```html
<style type="text/css">
  #aside-content .card-widget#card-wechat {
    background: #fafbfb;
    display: flex;
    justify-content: center;
    align-content: center;
    padding: 0;
    cursor: pointer;
    border: none;
    height: 110px;
  }
</style>

```

**Comment by carolcoral** [comment]
代码已合并 https://github.com/liuzhihang/halo-theme-hao/pull/612
