### ISSUE TITLE
[bug]首页的瞬间说说不显示东西和右键菜单与文章的复制链接、右下角悬浮操作按钮绑定

### ISSUE THREAD

**Issue by mhdy2233** [liuzhihang/halo-theme-hao#623]
### 是什么版本出现了此问题？

2.11.3

### 在线站点地址

https://bk.mhdyapp.buzz

### 发生了什么？

右键菜单与文章的复制链接、右下角悬浮操作按钮绑定

**Comment by carolcoral** [comment]
1. `右键菜单的复制`等功能需要你的站点使用`https`
2. 首页`瞬间`说说问题已经有反馈，正在排查中

**Comment by mhdy2233** [comment]
似乎是我没有表达清楚，关闭右键菜单后文章底部的复制链接和简繁替换无法使用。

**Comment by carolcoral** [comment]
> 似乎是我没有表达清楚，关闭右键菜单后文章底部的复制链接和简繁替换无法使用。

嗯，确实存在问题

**Comment by carolcoral** [comment]
@chengzhongxue 关闭`右键菜单`后触发复制功能提示方法未定义。
* version: 1.4.7-beta2

<img width="1060" alt="image" src="https://github.com/liuzhihang/halo-theme-hao/assets/8952687/4def2f0c-3104-4ac1-ba69-31736ce0e054">

**Comment by carolcoral** [comment]
`瞬间`显示问题已在 `1.4.7-beta3` 版本中修复

**Comment by mhdy2233** [comment]
> `瞬间`显示问题已在 `1.4.7-beta3` 版本中修复

目前的主题版本为1.4.7-beta3
瞬间版本为1.4.0
halo版本为2.11.3
网站为https://bk.mhdyapp.buzz
貌似并没有解决问题，通过升级重装过，没有解决
![](https://fj.mhdyapp.buzz/fujian/2024-01-11-21-20-43-2024-01-11-21-20-43)
![](https://fj.mhdyapp.buzz/fujian/2024-01-11-21-20-25-2024-01-11-21-20-25)
![](https://fj.mhdyapp.buzz/fujian/2024-01-11-21-18-45-2024-01-11-21-18-45)

**Comment by mhdy2233** [comment]
> > `瞬间`显示问题已在 `1.4.7-beta3` 版本中修复
> 
> 目前的主题版本为1.4.7-beta3 瞬间版本为1.4.0 halo版本为2.11.3 网站为https://bk.mhdyapp.buzz 貌似并没有解决问题，通过升级重装过，没有解决 <img alt="image" width="50%" src="https://camo.githubusercontent.com/42b71d904e622598a0ce8580327285a481925e6f4193e27d03c0b5ff448ce760/68747470733a2f2f666a2e6d6864796170702e62757a7a2f66756a69616e2f323032342d30312d31312d32312d32302d34332d323032342d30312d31312d32312d32302d3433"> <img alt="image" width="50%" src="https://camo.githubusercontent.com/0582d7667e5e3f86c413b827ef0fae5993db9f6601b5f836597624a4d5d25f5f/68747470733a2f2f666a2e6d6864796170702e62757a7a2f66756a69616e2f323032342d30312d31312d32312d32302d32352d323032342d30312d31312d32312d32302d3235"> <img alt="image" width="50%" src="https://camo.githubusercontent.com/e458e43e98b412e089e92674f9de38d77e852c49543e97cc93fff0c01a75ed3e/68747470733a2f2f666a2e6d6864796170702e62757a7a2f66756a69616e2f323032342d30312d31312d32312d31382d34352d323032342d30312d31312d32312d31382d3435">

我重新安装瞬间1.2可行，1.3可行，安装到1.4后可行了应该是得重新安装一遍
