### ISSUE TITLE
通过自定义链接添加的页面下面会出现评论区

### ISSUE THREAD

**Issue by Omoinemie** [liuzhihang/halo-theme-hao#634]
### 是什么版本出现了此问题？

1.4.6

### 发生了什么？

通过链接创建的页面会出现评论区，这个是个bug，其他主题和官方的都没有这个问题。
![image](https://github.com/liuzhihang/halo-theme-hao/assets/31991443/65b393e5-e22a-4bd7-b0cd-88591f0a702a)
![image](https://github.com/liuzhihang/halo-theme-hao/assets/31991443/35604553-0b8e-45fe-940c-15efad4c1435)
![image](https://github.com/liuzhihang/halo-theme-hao/assets/31991443/f59ca76e-66e3-4ce7-aa51-1186da5de824)

**Comment by carolcoral** [comment]
<img width="1308" alt="image" src="https://github.com/liuzhihang/halo-theme-hao/assets/8952687/4f8c03eb-49ae-4ee6-8f20-04fc3ece8b36">

**Comment by carolcoral** [comment]
看看你的halo版本，你可以更新到最新的2.11.4后再试试，页面设置是否存在评论区是博客系统设置的

**Comment by Omoinemie** [comment]
> 看看你的halo版本，你可以更新到最新的2.11.4后再试试，页面设置是否存在评论区是博客系统设置的
版本
2.11.3
我不是通过新建页面再添加菜单，而是新建菜单直接选择的自定义链接，填的/photos，这个没地方关闭评论，我问了halo开发，他说是主题适配的问题

**Comment by carolcoral** [comment]
> > 看看你的halo版本，你可以更新到最新的2.11.4后再试试，页面设置是否存在评论区是博客系统设置的
> > 版本
> > 2.11.3
> > 我不是通过新建页面再添加菜单，而是新建菜单直接选择的自定义链接，填的/photos，这个没地方关闭评论，我问了halo开发，他说是主题适配的问题

这个肯定没地方去控制啊，控制页面是否展示评论功能都是在你新建页面或者进入对应页面设置里面去控制的啊。怎么可能在菜单中去控制。
