### ISSUE TITLE
希望下一个版本文章 AI 摘要框可自定义修改！

### ISSUE THREAD

**Issue by Joneeys** [liuzhihang/halo-theme-hao#635]
### 你当前使用的版本

1.4.6

### 描述一下此特性

文章内 AI 摘要框，后台可自定义修改，如图框起的部分。
提一个小bug，右上角按钮与文章匹配颜色不一致，如图所示。
![WX20240115-230213@2x](https://github.com/liuzhihang/halo-theme-hao/assets/156687438/8a466f8e-b7d9-4ae6-b617-239e5ec328a3)

**Comment by carolcoral** [comment]
`文章内 AI 摘要框，后台可自定义修改，如图框起的部分。` - 暂不考虑做配置（配置过细）
`提一个小bug，右上角按钮与文章匹配颜色不一致，如图所示。` - 固定颜色，用于区分显示版权或标识信息
