### ISSUE TITLE
我的设备这个页面什么时候上线

### ISSUE THREAD

**Issue by king-zhangbn** [liuzhihang/halo-theme-hao#647]
### 你当前使用的版本

1.4.7

### 描述一下此特性

我的设备这个页面什么时候上线

**Comment by carolcoral** [comment]
<img width="1659" alt="image" src="https://github.com/liuzhihang/halo-theme-hao/assets/8952687/45528ab0-df5f-421e-8539-f914c81cebcb">
<img width="1675" alt="image" src="https://github.com/liuzhihang/halo-theme-hao/assets/8952687/b427c52f-5e28-4cd6-aa83-002e6dda1176">

固定后缀 `/equipments`
