### ISSUE TITLE
自定义页面评论无法关闭

### ISSUE THREAD

**Issue by Omoinemie** [liuzhihang/halo-theme-hao#651]
### 是什么版本出现了此问题？

1.4.7

### 发生了什么？

问题：页面设置中关闭了评论，添加自定义页面后评论依然存在。
问题页面：
【瞬间】：http://www.web.vomiku.com:7080/moments
【相册】：http://www.web.vomiku.com:7080/photos

![image](https://github.com/liuzhihang/halo-theme-hao/assets/31991443/a25b3a04-7136-4c35-a281-a7fc9ad8d089)

![image](https://github.com/liuzhihang/halo-theme-hao/assets/31991443/1538c06f-12c6-457b-a329-67c3c3afe440)

![image](https://github.com/liuzhihang/halo-theme-hao/assets/31991443/499780e1-3df9-4164-9fc6-dabd1fd65cca)

**Comment by carolcoral** [comment]
建议查看是否为你站点的缓存问题，或者使用了某些“自定义模板”导致的问题。
我使用最新版本主题经过尝试未复现你的问题

<img width="1331" alt="image" src="https://github.com/liuzhihang/halo-theme-hao/assets/8952687/03ea561d-ef58-4ad0-b386-a93a4c572e87">

**Comment by Omoinemie** [comment]
> 建议查看是否为你站点的缓存问题，或者使用了某些“自定义模板”导致的问题。 我使用最新版本主题经过尝试未复现你的问题
> 
> <img alt="image" width="1331" src="https://private-user-images.githubusercontent.com/8952687/300666113-03ea561d-ef58-4ad0-b386-a93a4c572e87.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY1OTYzNzUsIm5iZiI6MTcwNjU5NjA3NSwicGF0aCI6Ii84OTUyNjg3LzMwMDY2NjExMy0wM2VhNTYxZC1lZjU4LTRhZDAtYjM4Ni1hOTNhNGM1NzJlODcucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDEzMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMzBUMDYyNzU1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NWE3OGY4MTVhMGU3NmEyMTU0ZjM4MDZmOWM3MTdhNTJiNDIxODIxYzY0NTNmMTEyNzg0OTBmZWZlODY4ZmUzOSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.EpKDYLrHto3AkAZL9Wj7CgjnZLA9oC7JpI-22w6OfR8">

其他页面评论是可以关闭的，但瞬间和图库这两个关闭不了，采用[/moments]和[/photos]这两个链接，就不得行

**Comment by Omoinemie** [comment]
我是全新安装测试的也还是一样

**Comment by carolcoral** [comment]
这两个地址是插件提供的url，里面的页面是插件的自定义页面，无法通过`页面`去控制的，和主题无关，建议找插件开发者进行沟通
