### ISSUE TITLE
移动端 显示不正常

### ISSUE THREAD

**Issue by haoanlan** [liuzhihang/halo-theme-hao#652]
### 是什么版本出现了此问题？

1.4.7

### 在线站点地址

https://blog.404notfound.space/

### 发生了什么？

移动端 显示不正常  能否在小于1200px时 categoryItem只显示前两个使其更加美观。

### 附加信息

![image](https://github.com/liuzhihang/halo-theme-hao/assets/90305105/8d34aabb-d408-48c6-b66a-2e4240f99706)

**Comment by carolcoral** [comment]
已优化，下个版本更新

**Comment by carolcoral** [comment]
新版本下载地址：
境外：https://github.com/liuzhihang/halo-theme-hao/releases/tag/v1.4.8-beta1
国内：https://gitea.cnkj.site/halo/halo-theme-hao/releases/tag/v1.4.8-beta1
