### ISSUE TITLE
首页中侧栏的爱发电模块间距问题

### ISSUE THREAD

**Issue by UPToZ-Core** [liuzhihang/halo-theme-hao#655]
### 是什么版本出现了此问题？

1.4.7

### 在线站点地址

https://blog.uptoz.cn

### 发生了什么？

![image](https://github.com/liuzhihang/halo-theme-hao/assets/73866989/1eae7dae-053b-48f6-8e95-870f28039d1a)
首页中的侧栏，爱发电模块与其他模块没有间距。

**Comment by carolcoral** [comment]
@chengzhongxue 等鱼总修复

**Comment by chengzhongxue** [comment]
自己改改不就好了

**Comment by carolcoral** [comment]
讲真，我这儿好的

**Comment by carolcoral** [comment]
修了，下个版本发

**Comment by carolcoral** [comment]
新版本下载地址：
境外：https://github.com/liuzhihang/halo-theme-hao/releases/tag/v1.4.8-beta1
国内：https://gitea.cnkj.site/halo/halo-theme-hao/releases/tag/v1.4.8-beta1
