### ISSUE TITLE
移动端主菜单不显示

### ISSUE THREAD

**Issue by iam189cm** [liuzhihang/halo-theme-hao#657]
### 是什么版本出现了此问题？

1.4.7

### 发生了什么？

已经在导航栏设置了移动显示主菜单显示，但实际上没有显示
![2024-02-03-11-13-01](https://github.com/liuzhihang/halo-theme-hao/assets/54161514/5d3faf26-3d99-41dd-8c36-98cd70244df2)
![2024-02-03-11-13-22](https://github.com/liuzhihang/halo-theme-hao/assets/54161514/a00d013e-4f1b-4a85-82a2-e9912fe37597)

**Comment by carolcoral** [comment]
建议查看文档哈，有详细说明：https://www.yuque.com/liuzhihangs/halo-theme-hao/xakr7q

**Comment by iam189cm** [comment]
OK
