### ISSUE TITLE
第一屏bug

### ISSUE THREAD

**Issue by rational-stars** [liuzhihang/halo-theme-hao#658]
### 是什么版本出现了此问题？

1.4.7

### 在线站点地址

https://rational-stars.top

### 发生了什么？

第一屏设置的是隐藏 打开控制台 刷新。会出现第一屏 关闭控制台 刷新就没有第一屏了   视频压缩了 有点糊哈

### 附加信息

https://github.com/liuzhihang/halo-theme-hao/assets/65513250/ae6b4de2-1c7f-4386-b426-d5c7fa69ff59

**Comment by carolcoral** [comment]
是不是设置了缓存：
1. ng代理服务缓存
2. halo服务缓存（docker compose或者docker等启动的时候可配参数）
3. 本地缓存

**Comment by carolcoral** [comment]
长时间未回复，手动关闭issue
