### ISSUE TITLE
新增关于页打赏头像支持格式不完善

### ISSUE THREAD

**Issue by 666ghj** [liuzhihang/halo-theme-hao#660]
### 是什么版本出现了此问题？

1.4.7

### 在线站点地址

[_网址链接_](http://59.110.174.16:8090/about)

### 发生了什么？

在添加头像后格式发生混乱，如图
<img width="1038" alt="bug反馈" src="https://github.com/liuzhihang/halo-theme-hao/assets/110395318/aaf8db25-5091-45a3-8790-63128b0624a1">

**Comment by 666ghj** [comment]
![Uploading PixPin_2024-02-06_10-04-50.jpg…]()

**Comment by 666ghj** [comment]
赞赏页配置如图
![网页捕获_6-2-2024_102912_59 110 174 16](https://github.com/liuzhihang/halo-theme-hao/assets/110395318/a1cf824d-db26-414d-952d-5078d4da7959)

**Comment by 666ghj** [comment]
标记金额：10

第一个
名称：轩
金额：0.38
日期：2024/01/10
头像：https://lovexl-oss.oss-cn-beijing.aliyuncs.com/bed/202402061038730.jpg

第二个
名称：身高两米八
金额：0.88
日期：2024/01/10
头像：https://lovexl-oss.oss-cn-beijing.aliyuncs.com/bed/202402061039024.jpg

第三个
名称：小梁
金额：20
日期：2024/01/10
头像：https://lovexl-oss.oss-cn-beijing.aliyuncs.com/bed/202402061039781.jpg

第四个
名称：CoCo
金额：18
日期：2024/01/10
头像：https://lovexl-oss.oss-cn-beijing.aliyuncs.com/bed/202402061040680.jpg

**Comment by carolcoral** [comment]
新版本下载地址：
境外：https://github.com/liuzhihang/halo-theme-hao/releases/tag/v1.4.8-beta1
国内：https://gitea.cnkj.site/halo/halo-theme-hao/releases/tag/v1.4.8-beta1
