### ISSUE TITLE
为什么无法显示文章摘要？

### ISSUE THREAD

**Issue by wenjing-xin** [liuzhihang/halo-theme-hao#670]
### 是什么版本出现了此问题？

Halo版本：2.12.2；Halo-theme-hao:1.4.8

### 在线站点地址

https://wengjing.xin

### 发生了什么？

文章设置中已经开启了自动生成摘要，但是不显示。具体信息可以在我的小破站里看到，如果是我设置有问题，望不吝赐教！

**Comment by carolcoral** [comment]
自动生成摘要需要AI令牌，令牌是需要购买的

**Comment by wenjing-xin** [comment]
> 自动生成摘要需要AI令牌，令牌是需要购买的

我说的文章列表的摘要，并没有说AI全文摘要，这个我已经配置好了，
![image](https://github.com/liuzhihang/halo-theme-hao/assets/130843859/070b7c58-0d3e-4d65-9767-072e9500675e)

**Comment by wenjing-xin** [comment]
![image](https://github.com/liuzhihang/halo-theme-hao/assets/130843859/e56332ae-4185-48d3-b8bd-6a2344e14085)
zai bu cho再补充一下，这个摘要是合适的

**Comment by carolcoral** [comment]
<img width="532" alt="image" src="https://github.com/liuzhihang/halo-theme-hao/assets/8952687/068aa5aa-3163-4ea4-80ac-da5c8bd9241e">

另外这个是正确的，因为在几个版本前文章列表页面中展示文章的摘要会导致移动端情况下出现`错行`、`覆盖`等问题，因此暂时取消了该功能，以后再看情况是否恢复

**Comment by wenjing-xin** [comment]
> 以后再看情况是否恢复

好的，谢谢回复
