### ISSUE TITLE
已登录状态下 右上角的登录图标会消失

### ISSUE THREAD

**Issue by funtime1** [liuzhihang/halo-theme-hao#677]
### 是什么版本出现了此问题？

1.4.8

### 发生了什么？

登录前：
![image](https://github.com/liuzhihang/halo-theme-hao/assets/90565575/74db03af-9593-4187-8de9-c749901477d9)

登录后：![image](https://github.com/liuzhihang/halo-theme-hao/assets/90565575/9b78e55e-6daa-491f-8718-337416caff12)

**Comment by carolcoral** [comment]
你的网址多少，我这边看看，我本地不太好复现

**Comment by carolcoral** [comment]
<img width="282" alt="image" src="https://github.com/liuzhihang/halo-theme-hao/assets/8952687/283e0e03-e80c-406e-8451-c28efd22d44b">

正常登录后显示的是登录用户的头像，麻烦看看是不是头像没有设置或者设置了但是没有设置对呢
