### ISSUE TITLE
图库顶部空白区域是什么内容？

### ISSUE THREAD

**Issue by Omoinemie** [liuzhihang/halo-theme-hao#683]
### 是什么版本出现了此问题？

1.4.8

### 在线站点地址

http://www.web.vomiku.com:7080/photos
http://www.web.vomiku.com:7080/tuku

### 发生了什么？

顶部上面有一块空白区域，没找到设置内容得地方，是做什么用的？

### 附加信息

![image](https://github.com/liuzhihang/halo-theme-hao/assets/31991443/cb55249b-9ba1-4721-97f4-4e8240b18233)

**Comment by carolcoral** [comment]
重复issues，关闭
