### ISSUE TITLE
怎么使用LXGW WenKai Screen这款字体呢？

### ISSUE THREAD

**Issue by FunkyGod** [liuzhihang/halo-theme-hao#690]
### 你当前使用的版本

2.12.0

### 描述一下此特性

求指导使用“LXGW WenKai Screen”这款字体

**Comment by carolcoral** [comment]
在设置中使用全局注入方式引入字体

**Comment by carolcoral** [comment]
主题-样式-全局字体中设置

<img width="868" alt="image" src="https://github.com/liuzhihang/halo-theme-hao/assets/8952687/a9bbd93a-d94e-411d-89a1-a6343bfff015">

**Comment by FunkyGod** [comment]
> 主题-样式-全局字体中设置
> 
> <img alt="image" width="868" src="https://private-user-images.githubusercontent.com/8952687/315196470-a9bbd93a-d94e-411d-89a1-a6343bfff015.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE0MzIwOTEsIm5iZiI6MTcxMTQzMTc5MSwicGF0aCI6Ii84OTUyNjg3LzMxNTE5NjQ3MC1hOWJiZDkzYS1kOTRlLTQxMWQtODlhMS1hNjM0M2JmZmYwMTUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMyNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMjZUMDU0MzExWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OTQxOTgyNDBjOTVmY2U0N2Q3YTY4NTFhZmQxMTcxZjFlMWZmNzNjODA3OTBiY2NhMzM2ZDExZmExMjAwNTVkZiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.uTZqtyfUfecmdf7kxnf55_kL2GyqeqzrYi5oUDEtzHQ">

![image](https://github.com/liuzhihang/halo-theme-hao/assets/39259580/181e69b0-9176-463e-84ae-eb3cd70e638b)

没有生效呢
