### ISSUE TITLE
有一个图裂了

### ISSUE THREAD

**Issue by Danborad** [liuzhihang/halo-theme-hao#695]
### 是什么版本出现了此问题？

1.48

### 发生了什么？

打开网页或者刷新网页，网页中心有一个加装的图标应该是，图裂了，然后在主题管理里面，主题缩略图也裂了

### 附加信息

![Snipaste_2024-03-19_15-45-27](https://github.com/liuzhihang/halo-theme-hao/assets/25317578/a93f7bc8-b1c5-45b7-9a81-9f309e58fe7e)

![QQ截图20240319154554](https://github.com/liuzhihang/halo-theme-hao/assets/25317578/3ce59b1a-987d-44ef-8271-18b935e4760c)
![QQ截图20240319154632](https://github.com/liuzhihang/halo-theme-hao/assets/25317578/fa2aee39-c4dd-45c3-95ae-c44e1e67c61f)

**Comment by carolcoral** [comment]
加载图片你可以在主题设置中替换，两外两个图片是主题开发者的oss挂了，不影响使用

**Comment by carolcoral** [comment]
加载图片修改方式：
主题-其他设置-加载图片

<img width="551" alt="image" src="https://github.com/liuzhihang/halo-theme-hao/assets/8952687/bb3f339a-214b-45c3-975b-a921a44b235b">

**Comment by Danborad** [comment]
好的，感谢
