### ISSUE TITLE
我在设置文章页底部的“阅读建议 ”为“0”时，并不生效

### ISSUE THREAD

**Issue by wuzhuwei111** [liuzhihang/halo-theme-hao#75]
### 你当前使用的版本

1.0.7

### 描述一下此特性

我在设置文章页底部的“阅读建议 ”为“0”时（主题-文章-阅读建议），并不生效。其实我就是想关闭他，但是没有关闭选项，只有数量调整，但是当我调整为0时，其实时全部显示，我希望这个可以改进，谢谢

**Comment by shy-share** [comment]
@wuzhuwei111 已经修复
