### ISSUE TITLE
随机图每篇文章图片一样

### ISSUE THREAD

**Issue by shy-share** [liuzhihang/halo-theme-hao#80]
### 是什么版本出现了此问题？

1.0.7

### 发生了什么？

![image](https://user-images.githubusercontent.com/50973219/217456398-21d4daad-fd2c-416f-b5c9-7e8a47f8906f.png)
理想情况 应该是 每篇文章都是不一样的图片，而且都是从随机图片地址获取来的

**Comment by shy-share** [comment]
现在发现是 其实是首页的时候 只调用了一次 随机图api导致的每个文章的图片都是一样的，但是我不知道如何让每个文章都去发起一次随机图请求。 @JohnNiang @liuzhihang 你们知道吗？

**Comment by AirboZH** [comment]
> 现在发现是 其实是首页的时候 只调用了一次 随机图api导致的每个文章的图片都是一样的，但是我不知道如何让每个文章都去发起一次随机图请求。 @JohnNiang @liuzhihang 你们知道吗？

一个比较取巧的办法是给每个url加不同的参数，让浏览器以为他们是不同的链接，但是这些参数又会被api忽略，可以达到预期效果
![image](https://user-images.githubusercontent.com/50261327/217709387-8e5f79e0-c15c-447e-bcea-683880f44a6c.png)

**Comment by JohnNiang** [comment]
根据 https://github.com/liuzhihang/halo-theme-hao/issues/80#issuecomment-1423566283 提供的思路，看可以考虑在主题中拼接一个 post name 参数到 img 的 src 属性。

**Comment by shy-share** [comment]
> 根据 [#80 (comment)](https://github.com/liuzhihang/halo-theme-hao/issues/80#issuecomment-1423566283) 提供的思路，看可以考虑在主题中拼接一个 post name 参数到 img 的 src 属性。
首页的图片是在下面这段代码的
https://github.com/liuzhihang/halo-theme-hao/blob/16b236dd8c88a8153115e32520ecb21596c732c9/templates/modules/post-list.html#L15-L21
那这种方式应该只限于 随机图api可以在后面加参数的情况

**Comment by AirboZH** [comment]
一样的
```html
  <img class="post_bg entered loaded" loading="lazy"
                     th:alt="${post.status.excerpt}"
                     th:src='${#strings.isEmpty(post.spec.cover) ? theme.config.layout.postRandomImg+","+iStat : post.spec.cover}'>
```
![image](https://user-images.githubusercontent.com/50261327/217712696-a0e290c0-996f-46b9-8d5c-28861e40eadc.png)

**Comment by AirboZH** [comment]
拼 `iStat.index` 就可以了，上图中的 `iStat` 数据有些多

**Comment by AirboZH** [comment]
也测试了另外一个，拼接参数的思路倒是没什么问题，只是原url没有 `?` 的时候应该拼 '?' 上去
![image](https://user-images.githubusercontent.com/50261327/217713554-d9af7956-4a67-441a-9045-1e7c27d3af24.png)

**Comment by AirboZH** [comment]
```
 th:with='postItems=${posts.items},postRandomImg=${#strings.contains(theme.config.layout.postRandomImg,"?") ? theme.config.layout.postRandomImg : theme.config.layout.postRandomImg+"?"}'
……
 th:src='${#strings.isEmpty(post.spec.cover) ? postRandomImg+","+iStat.index : post.spec.cover}'>
```
