### ISSUE TITLE
顶部导航栏建议加上背景颜色，白底黑字，黑底白字，目前浅色头部图片无法看清导航字体（如图）

### ISSUE THREAD

**Issue by wuzhuwei111** [liuzhihang/halo-theme-hao#81]
### 你当前使用的版本

1.0.7-main

### 描述一下此特性

顶部导航栏建议加上背景颜色，白底黑字，黑底白字，目前浅色头部图片无法看清导航字体（如图）![微信截图_20230209102022](https://www.wuzhuwei.work/upload/2023/02/%E5%BE%AE%E4%BF%A1%E6%88%AA%E5%9B%BE_20230209102022.png)
![微信截图_20230209101338](https://www.wuzhuwei.work/upload/2023/02/%E5%BE%AE%E4%BF%A1%E6%88%AA%E5%9B%BE_20230209101338.png)

**Comment by shy-share** [comment]
@wuzhuwei111 你这是自己设置了什么吗？还是说因为你用的图片颜色都是偏浅色导致的？我本地是正常显示的  
![image](https://user-images.githubusercontent.com/50973219/217710984-3c089b71-0686-4ca7-a8bf-1a9ed8f449bb.png)

**Comment by wuzhuwei111** [comment]
@shy-share 没有设置，下拉浏览是有毛玻璃效果的，进入页面不下拉的情况下，白色背景旧会和白色字体一样颜色

**Comment by AirboZH** [comment]
> @shy-share 没有设置，下拉浏览是有毛玻璃效果的，进入页面不下拉的情况下，白色背景旧会和白色字体一样颜色

可以提供网址么，按理说这个图片上会加一个深色纯色的背景方便显示白色字体，如图：
![image](https://user-images.githubusercontent.com/50261327/217723655-fd5bcf29-2905-4ae1-b046-2e89e9172859.png)

**Comment by wuzhuwei111** [comment]
@AirboZH 2.0版本目前还没有用到生产环境，所有没有放到公网上。

**Comment by AirboZH** [comment]
> @AirboZH 2.0版本目前还没有用到生产环境，所有没有放到公网上。
@wuzhuwei111 

可以从我的示例图中看到左下角到右上角是一个深色到透明的渐变。这才是正常的样子。
感觉你图片中展示的不是正常情况，可以先尝试刷新以及更新缓存的方式来正确加载CSS文件
你可以尝试切换深色模式和浅色模式来调整一些css可能产生的bug。
也可以在控制台-主题-文章-动态主色 关闭动态主色按钮来给这部分一个固定的蓝色
如：
![image](https://user-images.githubusercontent.com/50261327/217738288-4d5e0dfe-ff31-4932-bf6f-dc1aa63141fd.png)


另外，关注一下浏览器控制台和Network部分是否有未正常加载的文件以及报错信息

**Comment by AirboZH** [comment]
can't repro
