### ISSUE TITLE
侧边栏最新评论显示错误

### ISSUE THREAD

**Issue by shy-share** [liuzhihang/halo-theme-hao#87]
### 是什么版本出现了此问题？

1.0.7

### 在线站点地址

https://liuzhihang.com/

### 发生了什么？

![image](https://user-images.githubusercontent.com/50973219/217773874-84fed76e-0dfd-4859-a5a0-9ad77549519f.png)
评论模块社区已经提供了，目前是主题没有适配

**Comment by AirboZH** [comment]
需要Comment插件提供的接口 https://github.com/halo-sigs/plugin-comment-widget/issues/14

**Comment by jkjoy** [comment]
安装了这个插件还是不行啊
