### ISSUE TITLE
toc消失

### ISSUE THREAD

**Issue by Steven-WZH** [liuzhihang/halo-theme-hao#92]
### 是什么版本出现了此问题？

1.0.7

### 在线站点地址

https://blog.steven.tk/

### 发生了什么？

toc消失了

### 附加信息

![image](https://user-images.githubusercontent.com/113268133/217810671-7dc0e4c1-1e51-462e-bf91-12999a08c35d.png)

**Comment by jiuyue52** [comment]
可以去目录插件重新点一下保存，不出意外应该可以解决

**Comment by Steven-WZH** [comment]
e
之前没加插件
现在加了之后目录直接消失了

**Comment by Steven-WZH** [comment]
> e 之前没加插件 现在加了之后目录直接消失了

现在好了，谢谢
