### ISSUE TITLE
归档页适配

### ISSUE THREAD

**Issue by shy-share** [liuzhihang/halo-theme-hao#93]
### 你当前使用的版本

1.0.7

### 描述一下此特性

跟仙总沟通了一下，目前应该是提供了归档页的api的，需要主题适配

**Comment by AirboZH** [comment]
api地址是...？

**Comment by shy-share** [comment]
> api地址是...？

不知道 只是知道应该有

**Comment by shy-share** [comment]
@AirboZH 我按照官方搞的 但是页面是空白的
![image](https://user-images.githubusercontent.com/50973219/217988645-f4d7a90b-4cb1-4264-a46a-e76a894e8299.png)
![image](https://user-images.githubusercontent.com/50973219/217988670-5711b415-03a9-4ea9-89b2-8bbfb9085274.png)

**Comment by AirboZH** [comment]
Assign 给我吧，按Heo网站的页面，加自己的数据进去 应该就可以了
https://blog.zhheo.com/archives/
