### ISSUE TITLE
手机端代码过长没有换行

### ISSUE THREAD

**Issue by Steven-WZH** [liuzhihang/halo-theme-hao#96]
### 是什么版本出现了此问题？

1.0.7

### 在线站点地址

https://blog.steven.tk/

### 发生了什么？

如题
还有就是这个主题适配官方的搜索插件的样式好奇怪，和导航栏连一起了

**Comment by AirboZH** [comment]
可以提供一下截图么我好想没有发现这个问题

**Comment by Steven-WZH** [comment]
oo不好意思，可能当时没加载玩导致没换行，现在解决了
